### ISSUE TITLE
Update Overhaul: Limit bundle builds to the master branch

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1000]
We're currently [building install bundles](https://github.com/tiny-pilot/tinypilot/blob/4e80a54878a6f90bf84a3af4ba3286653618929e/.circleci/config.yml#L51) on every commit. This is useful for now, as we're rapidly iterating on the bundle code. Once that code is stable, we'll add a filter so that we only build and upload bundles in the `master` branch.

**Comment by jdeanwallace** [comment]
FYI, https://github.com/tiny-pilot/tinypilot/issues/1005 adds an additional `build_debian_package` step to CircleCI which should also only run on the `master` branch. As a result, we should only address this issue once https://github.com/tiny-pilot/tinypilot/issues/1005 has been resolved.
