### ISSUE TITLE
Update Overhaul: Compress tarballs

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1002]
The tarball size is currently around ~4 MB~ 850KB (Community version).

We could save 10% or so by compressing it. That would save storage and bandwidth costs, and also speed up the download/install procedure a bit.

**Comment by jotaen4tinypilot** [comment]
Turns out, 3M of the tarball was the [`readme-assets`](https://github.com/tiny-pilot/tinypilot/tree/master/readme-assets) folder. Compression is still an easy win, but properly excluding non-needed files is more important.

**Comment by mtlynch** [comment]
@jotaen4tinypilot - I think we should do this in milestone 1 rather than milestone 3. Changing the filenames and the unpack command is going to be more complicated once TinyPilot Community is relying on the new update flow.

**Comment by jotaen4tinypilot** [comment]
Good point, I’ve moved it up to the 1st milestone.

Now that we have excluded the `readme-assets` folder, the net win isn’t that impressive anymore (819KB uncompressed vs 652KB compressed for the community bundle), but it’s an easy win and simple to implement, so I think it’s still better we have it right away.
