### ISSUE TITLE
Update Overaul: Refactoring idea: replace custom YAML-logic with `yq`?

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1004]
A significant part of the `./bundle/install` script is concerned with reading and writing from the `/home/tinypilot/settings.yml` file. It’s not super bad, but it also creates some noise.

https://github.com/tiny-pilot/tinypilot/blob/master/bundler/bundle/install#L46-L75

Our `grep`-ing is also not 100% robust, because it misses syntax variations like `ustreamer_capture_device: tc358743` vs. `ustreamer_capture_device: "tc358743"` or `ustreamer_capture_device:      tc358743`.

An option could be to use [yq](https://github.com/mikefarah/yq) (the YAML equivalent of [jq](https://stedolan.github.io/jq/)), which has a [feature for merging two files](https://mikefarah.gitbook.io/yq/v/v2.x/merge).

The downside is that we need to pull in another tool at install time.

But maybe worth to try out.

**Comment by mtlynch** [comment]
Fixed as a side-effect of #1554
