### ISSUE TITLE
Update Overhaul: replace git-based local version check with `VERSION` file

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1021]
[The current local version check is based on git](https://github.com/tiny-pilot/tinypilot/blob/296d8244ae284b0a3e4b3b535cbce1dd9bc38483/app/git.py#L15).

With the update overhaul, [we place a file called `VERSION` into the project root](https://github.com/tiny-pilot/tinypilot/blob/296d8244ae284b0a3e4b3b535cbce1dd9bc38483/Dockerfile#L31), that contains that same info as string.

So instead of running the git subcommand, we can just read and return the content from the `VERSION` file.

This task includes these questions:

- How should it behave locally (in development)? Since the `VERSION` file is not present then.

> **⚠️⚠️⚠️
> Please merge your work into the `update-overhaul` branch, not into `master`!
> (See [the note of the second milestone](https://github.com/tiny-pilot/tinypilot-pro/issues/445).)
> ⚠️⚠️⚠️**

**Comment by jdeanwallace** [comment]
Resolved in https://github.com/tiny-pilot/tinypilot/pull/1040
