### ISSUE TITLE
Update Overhaul: ask gatekeeper to figure out latest available version

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1022]
The [check for the latest available version](https://github.com/tiny-pilot/tinypilot/blob/296d8244ae284b0a3e4b3b535cbce1dd9bc38483/app/version.py#L19) currently uses [git under the hood](https://github.com/tiny-pilot/tinypilot/blob/296d8244ae284b0a3e4b3b535cbce1dd9bc38483/app/git.py#L31).

For the new update mechanism, we should [ask the gatekeeper REST API what the latest available version is](https://github.com/tiny-pilot/gatekeeper/issues/22).

> **⚠️⚠️⚠️
> Please merge your work into the `update-overhaul` branch, not into `master`!
> (See [the note of the second milestone](https://github.com/tiny-pilot/tinypilot-pro/issues/445).)
> ⚠️⚠️⚠️**

**Comment by jdeanwallace** [comment]
Resolved in https://github.com/tiny-pilot/tinypilot/pull/1043
