### ISSUE TITLE
Update Overhaul: Delegate to `get-tinypilot.sh` in `quick-install`

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1023]
For backwards-compatibility, we need to keep the `quick-install` script around, because [existing installations of TinyPilot rely on it being there](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/files/update#L15).

The internal logic of the script is replaced by the bundling logic altogether, so we can delete all the code and delegate to the `get-tinypilot.sh` script.

> **⚠️⚠️⚠️
> Please merge your work into the `update-overhaul` branch, not into `master`!
> (See [the note of the second milestone](https://github.com/tiny-pilot/tinypilot-pro/issues/445).)
> ⚠️⚠️⚠️**

**Comment by mtlynch** [comment]
Fixed in #1038
