### ISSUE TITLE
Problem starting tinypilot due to .flask-secret-key

### ISSUE THREAD

**Issue by VITOAMOROSO82** [tiny-pilot/tinypilot#1050]
## Description

Tinypilot service does not starts and nginx report a 502 bad gw error

## What's the behavior that you expect?

Tinypilot starts

## What's happening instead?

Tinypilot not starts

## What are the steps to reproduce this behavior?

1. Open TinyPilot in Chrome
3. See error

## Screenshots

_If applicable, add screenshots to help explain your problem._

## Logs

https://logs.tinypilotkvm.com/tRpmMmQh

**Comment by mtlynch** [comment]
It looks like your `/home/tinypilot` directory permissions are screwed up:

```bash
lug 08 16:56:36 raspberrypi python[1005]: 2022-07-08 16:56:36.785 secret_key      INFO No flask secret key found
lug 08 16:56:36 raspberrypi python[1005]: 2022-07-08 16:56:36.785 secret_key      INFO Creating new flask secret key at /home/tinypilot/.flask-secret-key
lug 08 16:56:36 raspberrypi python[1005]: Traceback (most recent call last):
lug 08 16:56:36 raspberrypi python[1005]:   File "/usr/lib/python3.7/shutil.py", line 563, in move
lug 08 16:56:36 raspberrypi python[1005]:     os.rename(src, real_dst)
lug 08 16:56:36 raspberrypi python[1005]: PermissionError: [Errno 13] Permission denied: '/tmp/tmpme5wbbha' -> '/home/tinypilot/.flask-secret-key'
```

Can you share the output of this command?

```bash
ls -ld /home/tinypilot && ls -l /home/tinypilot/.flask-secret-key
```

**Comment by VITOAMOROSO82** [comment]
> It looks like your `/home/tinypilot` directory permissions are screwed up:
> 
> ```shell
> lug 08 16:56:36 raspberrypi python[1005]: 2022-07-08 16:56:36.785 secret_key      INFO No flask secret key found
> lug 08 16:56:36 raspberrypi python[1005]: 2022-07-08 16:56:36.785 secret_key      INFO Creating new flask secret key at /home/tinypilot/.flask-secret-key
> lug 08 16:56:36 raspberrypi python[1005]: Traceback (most recent call last):
> lug 08 16:56:36 raspberrypi python[1005]:   File "/usr/lib/python3.7/shutil.py", line 563, in move
> lug 08 16:56:36 raspberrypi python[1005]:     os.rename(src, real_dst)
> lug 08 16:56:36 raspberrypi python[1005]: PermissionError: [Errno 13] Permission denied: '/tmp/tmpme5wbbha' -> '/home/tinypilot/.flask-secret-key'
> ```
> 
> Can you share the output of this command?
> 
> ```shell
> ls -ld /home/tinypilot && ls -l /home/tinypilot/.flask-secret-key
> ```

Yes you are true, coming from 1.5.2 version that didn't have this issue, I assigned the user "tinypilot" as owner of the folder and now It started.

Thank you
