### ISSUE TITLE
CircleCI: Bundle upload failing, probably due to configuration problem

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1095]
The [`upload_bundle` step is currently failing](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2452/workflows/6006351f-9e02-431c-93e8-cf83c12df939/jobs/9710) with configuration/permission errors:

<img width="1170" alt="Screenshot 2022-08-29 at 17 52 56" src="https://user-images.githubusercontent.com/83721279/187244025-7a201f63-675e-4e01-86e0-dab94eba2fd0.png">

This started with [the latest master commit](https://github.com/tiny-pilot/tinypilot/commit/c84fc79291bcce26f6572b7cf2b023e819cc425c), but that obviously is not the primary reason. I’ve also re-triggered the build manually, just to rule out that it was a one-off glitch.

<img width="752" alt="Screenshot 2022-08-29 at 18 00 05" src="https://user-images.githubusercontent.com/83721279/187244215-58ab958b-764b-464b-ba82-e6ea604beb6e.png">

The [respective environment variables are set](https://app.circleci.com/settings/project/github/tiny-pilot/tinypilot/environment-variables), but maybe something had changed on Backblaze’s end?

In the [pro repo](https://github.com/tiny-pilot/tinypilot-pro/commits/master), we don’t see this hapening.

**Comment by mtlynch** [comment]
Ah, thanks! I deleted some old Backblaze keys last week and must have accidentally deleted the live Community key. Fixed now:

![image](https://user-images.githubusercontent.com/7783288/187247574-572f7e93-8b7a-41de-aeb2-807b10897bb2.png)
