### ISSUE TITLE
Design: Support H264 in web UI

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1109]
Currently, H264 only works with a [manual command](https://tinypilotkvm.com/blog/whats-new-in-2022-05), and there's no indication in the web UI of which version is active or options to change it.

Let's sketch out what changes we need to make in order to support H264 in the web UI.

**Comment by jotaen4tinypilot** [comment]
I’ve compiled a task list from [the UI proposal](https://github.com/tiny-pilot/tinypilot-pro/pull/598) and added everything to the [2.5.1 project](https://github.com/orgs/tiny-pilot/projects/12/views/1):

- https://github.com/tiny-pilot/tinypilot/issues/1112
- https://github.com/tiny-pilot/ansible-role-ustreamer/issues/67
- https://github.com/tiny-pilot/ansible-role-tinypilot/issues/224
- https://github.com/tiny-pilot/tinypilot/issues/1113
- https://github.com/tiny-pilot/tinypilot/issues/1116
- https://github.com/tiny-pilot/tinypilot/issues/1114
- https://github.com/tiny-pilot/tinypilot/issues/1115
