### ISSUE TITLE
Ubuntu 22.04: Cannot load web interface after initial installation

### ISSUE THREAD

**Issue by billdenney** [tiny-pilot/tinypilot#1134]
## Description

Website for RPi not coming up with "502 Bad Gateway".

This is related to #1128

## What's the behavior that you expect?

Go to the RPi website (http://example.local) and it comes up.

## What's happening instead?

Website for RPi not coming up with "502 Bad Gateway".

## What are the steps to reproduce this behavior?

1. Install the current version of tinypilot
2. Open TinyPilot in Chrome
3. See error

## Screenshots

![image](https://user-images.githubusercontent.com/10359931/194354475-ab8cae44-674b-4111-bf40-fa1e707b85a3.png)

## Logs

http://logs.tinypilotkvm.com/TbFKNExM

**Comment by mtlynch** [comment]
Thanks for reporting this!

Can you try upgrading eventlet?

```bash
sudo sed --in-place 's/eventlet==0\.31\.0/eventlet==0.33.1/' /opt/tinypilot/requirements.txt && \
  sudo su tinypilot bash -c "cd /opt/tinypilot && . venv/bin/activate && pip install -r requirements.txt" && \
  sudo service tinypilot restart
```

**Comment by billdenney** [comment]
:smile: I was one step ahead on this one, but I did it a different way.  When I tried our command, it suggested that the way I did it was sufficient.  The output of your command is:

```
$ sudo sed --in-place 's/eventlet==0\.31\.0/eventlet==0.33.1/' /opt/tinypilot/requirements.txt && \
  sudo su tinypilot bash -c "cd /opt/tinypilot && . venv/bin/activate && pip install -r requirements.txt" && \
  sudo service tinypilot restart
Requirement already satisfied: eventlet==0.33.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.33.1)
Requirement already satisfied: Flask==1.1.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: Flask-SocketIO==5.0.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (5.0.1)
Requirement already satisfied: Flask-WTF==0.14.3 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (0.14.3)
Requirement already satisfied: pyyaml==5.4.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (5.4.1)
Requirement already satisfied: bidict==0.21.2 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (0.21.2)
Requirement already satisfied: click==7.1.2 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (7.1.2)
Requirement already satisfied: dnspython==1.16.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (1.16.0)
Requirement already satisfied: greenlet==1.1.3 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.1.3)
Requirement already satisfied: itsdangerous==1.1.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (1.1.0)
Requirement already satisfied: Jinja2==2.11.3 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (2.11.3)
Requirement already satisfied: MarkupSafe==1.1.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (1.1.1)
Requirement already satisfied: monotonic==1.5 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (1.5)
Requirement already satisfied: python-engineio==4.0.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (4.0.1)
Requirement already satisfied: python-socketio==5.1.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (5.1.0)
Requirement already satisfied: six==1.15.0 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (1.15.0)
Requirement already satisfied: Werkzeug==1.0.1 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (1.0.1)
Requirement already satisfied: WTForms==2.3.3 in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 22)) (2.3.3)
```

**Comment by mtlynch** [comment]
Your new error looks like a bug in dnspython. Maybe a later version will help?

```bash
sudo sed --in-place 's/dnspython==.*/dnspython==2.2.1/' /opt/tinypilot/requirements.txt && \
  sudo su tinypilot bash -c "cd /opt/tinypilot && . venv/bin/activate && pip install -r requirements.txt" && \
  sudo service tinypilot restart
```

**Comment by billdenney** [comment]
This is getting closer to success!  The webpage now loads, but the screen is black, and it's not clear if it's sending key presses.

At this point, it could also be a wiring issue since this is an initial installation.  But, the log suggests "111 unknown error" several times making me unsure what the issue is:  http://logs.tinypilotkvm.com/DKMtIYga

**Comment by mtlynch** [comment]
I'd recommend trying the setup first with Raspbian Buster to confirm the hardware all works and is connected already. I don't know of any users running TinyPilot on Ubuntu 22, so I'm not sure it's compatible yet.

**Comment by billdenney** [comment]
That makes sense.  Before I make the switch, are there any tests that can be done on the current system that may be lower-level to confirm that things are working?  What I'm thinking of are things like the following (though they may not be the right list):

* Here's how to confirm that the video capture device is recognized by ustreamer.
* Here's how to capture the current screen image with ustreamer as a .jpg to confirm that a screen is visible.
* Here's how to confirm that the keyboard output to the other computer is configured.
* Here's how to send key presses to the other computer (which should show up on the screen on that computer)

**Comment by mtlynch** [comment]
>Here's how to confirm that the video capture device is recognized by ustreamer.

This part looks like it's working. You can see in the uStreamer logs that it's picking up a video signal:

```
Oct 06 15:14:48 tinypilot ustreamer[825]: -- INFO  [17.331    stream] -- Creating pool JPEG with 1 workers ...
Oct 06 15:14:48 tinypilot ustreamer[825]: -- INFO  [17.332    stream] -- Capturing ...
```

>Here's how to capture the current screen image with ustreamer as a .jpg to confirm that a screen is visible.

If you visit the `/snapshot` route (e.g., http://tinypilot/snapshot), you should see the screen.

If you're seeing a pure black screen, it means that it's getting a signal from the target device, but the device is just outputting black pixels. If it fails to receive any signal, it shows the message "No Signal".

>Here's how to confirm that the keyboard output to the other computer is configured.
>Here's how to send key presses to the other computer (which should show up on the screen on that computer)

This is really just trying to type keyboard input into the TinyPilot interface and seeing if it shows up at the other end. If you have a physical view of the target machine's monitor, you can see if keystrokes are appearing on screen.

If the keystrokes are forwarding correctly, you'll see them in the bottom right corner of the screen. If they're failing, you'll see them appear in red. You'll also see messages indicating failure, which you have in your logs:

```text
Oct 06 16:00:10 tinypilot python[2151]: 2022-10-06 16:00:10.361 socket_api      ERROR [SENSITIVE] Failed to write key: Shift (keycode=ShiftLeft). Failed to write to HID interface: /dev/hidg0. Is USB cable connected? [/SENSITIVE]
```

`/dev/hidg0` is TinyPilot's emulated keyboard, and `/dev/hidg1` is TinyPilot's emulated mouse.

Different OSes have different steps you have to follow to switch the Pi's USB-C port over into device mode. TinyPilot's standard install will enable device mode on Raspbian Buster and Bullseye, but we haven't tested other platforms. We've received reports from users that Ubuntu 20 works, but no reports about Ubuntu 22.

**Comment by billdenney** [comment]
Thanks for the troubleshooting step suggestions.

1. http://tinypilot/snapshot Shows a black screen, so I'm pretty sure that it's working.
2. Keystrokes were showing in red at the bottom right of the screen.  I'm pretty sure that is a wiring issue.
3. The devices `/dev/hidg0` and `/dev/hidg1` exist in the `/dev` directory.
4. When I disconnected the video wire, the /screenshot page gave the following 404-like error instead of the "No Signal" image that you indicated above:  `{"code":404,"message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}`
5. I tried changing the wiring setup, and that didn't fix the issue
    1. I had been using the power connector (https://tinypilotkvm.com/product/tinypilot-power-connector) on a USB-A port on the RPi without power going to it directly.  I switched to using a USB-C on the RPi to USB-C on the server.
    2. I thought that perhaps device mode was specifically enabled on the USB-C port.  (I don't know if it's enabled on a port-by-port basis.)
    3. I then had a Canakit USB-C power button wire in between the RPi and the server.  I removed that.

My initial thought is that device mode is not successfully or correctly enabled on Ubuntu 22.04, based on the output of lsusb:

```
$ lsusb
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 534d:2109 MacroSilicon USB3.0 HD VIDEO
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Before I wipe to Raspbian, I'm going to wait for your thoughts:

* Do you want to troubleshoot #1140 ?
* I don't see a command `usb_gadget_activate` which seems to be required to active the keyboard and mouse USB gadget (https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/files/init-usb-gadget), but when digging a bit deeper, I found that `echo 1 > /sys/kernel/tracing/events/gadget/usb_gadget_activate/enable`  seemed to fix it!
    * But, by "fix it" I mean that the red letters at the bottom were no longer red (I still didn't see output on the screen, and it wasn't clear if the input was actually making it to the server.)

**Comment by mtlynch** [comment]
>Do you want to troubleshoot https://github.com/tiny-pilot/tinypilot/issues/1140 ?

It seems like the git commands are failing, but it's not a high priority bug that you need to keep the system image on hand.

>I don't see a command `usb_gadget_activate`

That's a bash function [TinyPilot defines](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/8a0b3f8bd5269dd03495cd3a345c053327c0142f/files/lib/usb-gadget.sh#L21). You should find it in `/opt/tinypilot-privileged/lib/usb-gadget.sh`

**Comment by mtlynch** [comment]
Closing this as it's been quiet and Ubuntu 22 is not officially supported.
