### ISSUE TITLE
H264: Indicate streaming mode in status bar

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1144]
We currently have a silent failover from H264 to MJPEG, if either Janus doesn’t come up at all, or if the connection is interrupted. Due to the automatic failover, the user might not notice that they are then streaming via MJPEG, rather than H264.

I’m not sure how much of an issue that actually is, but maybe users choose H264 for an important reason.

Below some ideas for how this could potentially be solved.

## Indicator in status bar

Either always present, showing `H.264` or `MJPEG`; or only present if H264 is enabled **and** active, otherwise hidden.

<img width="455" alt="Screenshot 2022-10-14 at 16 27 38" src="https://user-images.githubusercontent.com/83721279/195907613-a21c2ace-aff0-49f0-aacc-c33750ede86a.png">

## Error notification

As dialog (shown below) might be too obtrusive for a “proactive” error, but we could also come up with something more subtle.

<img width="1007" alt="Screenshot 2022-10-14 at 19 40 16" src="https://user-images.githubusercontent.com/83721279/195908693-09999196-f0f9-4a3d-bddb-39ec96da0f83.png">

**Comment by majuss** [comment]
The important reason is: the user is using a volume limited mobile connection and has to save bandwidth.

**Comment by mtlynch** [comment]
I don't think it should rise to the level of an error, but I think we should display either "H.264" or "MJPEG" in the status like you showed with a tooltip that explains it when the user hovers.
