### ISSUE TITLE
Allow users to upload and run scripts from the TinyPilot web interface

### ISSUE THREAD

**Issue by db39** [tiny-pilot/tinypilot#1168]
A user has requested this feature [via the forum](https://forum.tinypilotkvm.com/-442#post-8]). The user needs to execute a script to switch target machines with their KVM. And they would like to be able to execute these scripts on the TinyPilot web interface to do this.

**Comment by cghague** [comment]
We're tracking a more developed version of this request at https://github.com/tiny-pilot/tinypilot-pro/issues/1177. I'll close this as a duplicate issue.
