### ISSUE TITLE
e2e tests failing due to Janus installation

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1172]
Now [that the Ansible role installs Janus by default](https://github.com/tiny-pilot/ansible-role-tinypilot/issues/224) on the system, [the end-to-end tests are failing](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2646/workflows/0fe1fb3a-e825-4115-8768-2e7dfea1a3ac/jobs/10942), because the Janus Debian package can’t be installed in the Docker container (due to machine architecture mismatch).

In Pro, [we decided to abandon the e2e tests](https://github.com/tiny-pilot/tinypilot-pro/issues/538) a few months ago, because they caused too much trouble for too little value.

Shall we consider doing the same thing here? I’m not sure what an easy fix would be, since we can’t easily apply the same [hack as we did in `ansible-role-tinypilot`](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/adc64861752536245d3dcc83e00b9d4c4e616771/.circleci/config.yml#L39-L49).

**Comment by mtlynch** [comment]
Yeah, let's just drop it.
