### ISSUE TITLE
H264: Make MJPEG failover more obvious

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1187]
If the user had activated H.264, the stream can still failover to MJPEG in case the WebRTC connection is interrupted for whatever reason.

With the new [video stream indicator in the status bar](https://github.com/tiny-pilot/tinypilot/pull/1181), it’s obvious to the user what the current streaming mode is.

However, this can create an ambiguity in the UI, because the status bar would say “MJPEG”, whereas the video settings dialog would say “H.264”, and there is no indication or explanation about this mismatch.

# Potential solutions

Note that these could also be combined.

## “Failed state” of the status bar indicator

As suggested by @jdeanwallace [here](https://github.com/tiny-pilot/tinypilot/pull/1181#pullrequestreview-1171985404):

![screenshot](https://firebasestorage.googleapis.com/v0/b/codeapprove-prod.appspot.com/o/MTY2NzkwODI3NDY3NS1TY3JlZW4gU2hvdCAyMDIyLTExLTA4IGF0IDEzLjQ4LjU3LnBuZw.png?alt=media&token=ea0f656e-1520-49f6-b90e-37fddb8a89ea)

Or something like: (here with tooltip)

![Screenshot 2022-11-08 at 15 29 27](https://user-images.githubusercontent.com/83721279/200592635-a4c22ff6-6ba7-46f3-b24e-01d26845b7da.png)

## Warning in video settings dialog

If we detect a mismatch of the actual and desired mode in the video settings, we could display a warning there:

<img width="874" alt="Screenshot 2022-11-08 at 15 38 42" src="https://user-images.githubusercontent.com/83721279/200596857-dfe9c0e8-0edc-4f2a-bf90-4ca5381f166f.png">

# Discussion

I think it depends a bit how likely we deem this failover scenario to occur, as the above suggestions would require different effort for us to put into.

If we wanted to do something about this issue, then I think it’s not enough to just have a “failure icon” somewhere without any explanation. So we also need to have an error description, either in the tooltip itself, and/or in the video settings dialog. The latter is probably more important from a UX perspective, because the tooltip is easier to miss.

I suppose we could also leave it as it is, because the user might still figure out by themselves what’s going on, but it’s certainly not ideal.

**Comment by mtlynch** [comment]
I think the warning icon is good. Would that be difficult to implement?

Suggest error copy of:

>TinyPilot failed to stream the output of your target device using H.264 compression.
>
>See "System" > "Logs" for diagnostic details.
>
>Refreshing the page or restarting your device may fix the issue.

**Comment by mtlynch** [comment]
>One question as an aside: is it a thing that multiple users share the same TinyPilot device simultaneously? That’s the only scenario in which I can imagine inconsistencies in the frontend of one user, as the other user makes changes to the system.

It is, but I think it's okay if this scenario is a little rough for now. We already have this problem if two users are sharing a TinyPilot and one of them decreases the framerate or changes MJPEG quality, the other won't know what's going on. I think it's okay to be imperfect in the notifications here.
