### ISSUE TITLE
Mouse don't work on BIOS

### ISSUE THREAD

**Issue by eleksbai** [tiny-pilot/tinypilot#1189]
## Description

TinyPilot's keyboard and mouse don't work properly on HP laptop's bios, only the keyboard works

## What's the behavior that you expect?

Mouse works fine

## What's happening instead?

Keyboard works fine, mouse doesn't work

## What are the steps to reproduce this behavior?

1. Open TinyPilot in Chrome
2. Press esc on HP laptop to enter the StartUP Menu
3. At this time the web keyboard works but the web mouse does not work
4. Click F10 on the webpage to enter BIOS SETUP
5. At this time the web keyboard works but the web mouse does not work

## Screenshots

![image](https://user-images.githubusercontent.com/24777848/201000647-06908ea2-4ef6-4de9-9118-eb5707381443.png)
![image](https://user-images.githubusercontent.com/24777848/201000683-5b92cc08-ca3d-4012-a621-c88f1a8aaae4.png)
![image](https://user-images.githubusercontent.com/24777848/201000700-4f949e2e-fbb2-4d68-8ddb-0a5d93bb1624.png)

## Logs

https://logs.tinypilotkvm.com/AzORi1XW

**Comment by mtlynch** [comment]
Thanks for reporting this!

Which model HP laptop is this?

If you plug a physical USB mouse into the laptop, does it work? Are there any BIOS options for enabling external mouse input? Some laptops are picky about what external devices they'll interact with in BIOS.

**Comment by eleksbai** [comment]
Thank Bro!
my laptop is HP ProBook 440 G7 ,And my physical USB mouse into the laptop can work.

**Comment by eleksbai** [comment]
Thank Bro!
My laptop is HP ProBook 440 G7 ,And my physical USB mouse into the laptop can work.

> Thanks for reporting this!
> 
> Which model HP laptop is this?
> 
> If you plug a physical USB mouse into the laptop, does it work? Are there any BIOS options for enabling external mouse input? Some laptops are picky about what external devices they'll interact with in BIOS.
