### ISSUE TITLE
H264 audio: Accept multiple audio streams

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1191]
TinyPilot's H264 client implementation assumes that only a single media stream is available from the server: a video stream. When TinyPilot supports audio, there will be a video stream, then an audio stream, so we need to adjust our code to accept both streams.

Reference: https://github.com/pikvm/ustreamer/pull/181/files

**Comment by jdeanwallace** [comment]
> Reference: https://github.com/pikvm/ustreamer/pull/181/files

Noting that after the referenced changes were merged, [another change was added to the H264 docs](https://github.com/pikvm/ustreamer/commit/9b4f3229f2115714aba7fc590f348a08905b8cef#diff-13064c1fd700eaf3cab601f029e6d1cf1d867a660ebee0b18a7fbf01916cb379R190-R192) to instruct the Janus Plugin to initiate audio streaming:
```javascript
uStreamerPluginHandle.send({ message: { request: "watch", params: {audio: true} } });
```
