### ISSUE TITLE
Log whether the read-only filesystem is enabled in debug logs

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1205]
In some cases, users get confused that settings revert after reboot because they've forgotten that they've enabled the overlay filesystem / read-only filesystem.

We should include in the debug logs an indicator of whether the overlay filesystem is enabled.

**Comment by mtlynch** [comment]
@cghague - Can you see if you can find a way to determine whether or not the overlay filesystem is enabled or not from within a bash script?

**Comment by cghague** [comment]
@mtlynch - No problem! This should do the trick:

```bash
#!/bin/bash

grep -q "boot=overlay" /proc/cmdline
if [ $? -eq 0 ] ; then
  echo "The root partition is read-only!"
fi

findmnt /boot | grep -q " ro,"
if [ $? -eq 0 ] ; then
  echo "The boot partition is read-only!"
fi
```

The irony is that after testing this script on a read-only system I briefly wondered where it had gone after I rebooted! :rofl:

**Comment by mtlynch** [comment]
@cghague - Awesome! Could you submit a PR to integrate this into [the log collection script](https://github.com/tiny-pilot/tinypilot/blob/3c4193bb41748d58ce43cd6535bd52b11d1fccd9/debian-pkg/opt/tinypilot-privileged/scripts/collect-debug-logs)?

I'd like to make it so that the log file looks like this:

#### Enabled

```text
...
TinyPilot state
Read-only filesystem: on
temp=49.1'C
...
```

### Disabled

```text
...
TinyPilot state
Read-only filesystem: off
temp=49.1'C
...
```
