### ISSUE TITLE
LibreComputer LePotato - Installation Error

### ISSUE THREAD

**Issue by raghu-mp** [tiny-pilot/tinypilot#1234]
I am following the guide at https://gist.github.com/WarheadsSE/f90359e0f6955478c806ecbd04a643a3#file-h3-cc-otg-dts for LibreComputer Le Potato with latest armbian-22.11. While running the quick-install.sh getting the following error.

TASK [ansible-role-ustreamer : install Janus package and C header files] *****************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt_pkg.Error: E:The value 'stable' is invalid for APT::Default-Release as such a release is not available in the sources

I have checked /etc/apt/apt.conf.d for any mention of "stable" and did not find it. Any idea how to resolve this?

**Comment by mtlynch** [comment]
Thanks for reporting this!

Unfortunately, TinyPilot is only supported on the Raspberry Pi 4B. See [this thread](https://github.com/tiny-pilot/tinypilot/discussions/755) for a discussion of installing it on alternate hardware.
