### ISSUE TITLE
Install fails with Fatals

### ISSUE THREAD

**Issue by pacmac** [tiny-pilot/tinypilot#1254]
Just did a fresh install using the PI imager and the latest 32 bit Lite os.

Any idea on the cause / solutions:

```
TASK [ansible-role-ustreamer : check if legacy Janus package is installed] ****************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "dpkg-query --show --showformat='${Maintainer}' janus | grep TinyPilot", "delta": "0:00:00.105981", "end": "2023-01-09 11:54:56.392564", "msg": "non-zero return code", "rc": 1, "start": "2023-01-09 11:54:56.286583", "stderr": "dpkg-query: no packages found matching janus", "stderr_lines": ["dpkg-query: no packages found matching janus"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [ansible-role-ustreamer : check that OpenMax IL acceleration is only compiled on Raspberry Pi OS 10 (Buster) and earlier] ************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "OpenMax IL acceleration (OMX) is only available on Raspberry Pi OS 10 (Buster) and earlier."}
```

```
# uname -a
Linux tinypilot 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux
```

Thanks

**Comment by mtlynch** [comment]
Thanks for reporting this!

It sounds like you're specifying OMX encoding on a Raspbian Bullseye system, but Bullseye no longer has OMX, as it ended with Buster. The equivalent in Bullseye is `m2m-image`.

You're probably hitting #1110 or #1111.

Can you share some additional details?

* Hardware you're running on
* Install command (including any commands you ran beforehand to configure the install)

**Comment by pacmac** [comment]
Thanks, I'm using a pi zero 2w with the CSI board, the pre install command is:

```
TINYPILOT_SETTINGS="/home/tinypilot/settings.yml" && \
if [[ -f "${TINYPILOT_SETTINGS}" ]]; then
  sudo sed --in-place \
    --expression "/ustreamer_capture_device/d" \
    --expression "/ustreamer_encoder/d" \
    --expression "/ustreamer_format/d" \
    --expression "/ustreamer_resolution/d" ${TINYPILOT_SETTINGS} && \
    echo 'ustreamer_capture_device: tc358743' | sudo tee -a "${TINYPILOT_SETTINGS}"
else
  sudo useradd --create-home --system --user-group tinypilot && \
    echo 'ustreamer_capture_device: tc358743' | sudo tee -a "${TINYPILOT_SETTINGS}" && \
    sudo chown tinypilot:tinypilot "${TINYPILOT_SETTINGS}"
fi
```

I also tried running this just before curl, but it failed with same error:

```
sudo sed --in-place '/ustreamer_encoder: /d' \
    /home/tinypilot/settings.yml && \
  echo 'ustreamer_encoder: m2m-image' \
    | sudo tee --append /home/tinypilot/settings.yml
```

**Comment by mtlynch** [comment]
Hmm, I'm not sure why it's still trying to install OMX.

Can you share the output of this command?

```bash
cat /home/tinypilot/settings.yml
```

And can you share the full output from the install as a [gist](https://gist.github.com/)?

If you don't want to debug, the easiest workaround would be to install Raspbian Buster (aka "Raspberry Pi OS (Legacy)") instead.

**Comment by pacmac** [comment]
```
$ cat /home/tinypilot/settings.yml
ustreamer_capture_device: tc358743
ustreamer_encoder: m2m-image
```

Will do another fresh install and create a gist.

**Comment by pacmac** [comment]
There were errors, but install seems to have succeeded:

https://gist.github.com/pacmac/b64030dfcc1e2481ccbc0b54777741bc

**Comment by mtlynch** [comment]
Those errors are expected, so the install succeeded. Is the app working?

**Comment by pacmac** [comment]
"Is the app working?" - yep, thank you so much

**Comment by mtlynch** [comment]
Great, glad to hear it!

**Comment by pacmac** [comment]
excellent responses, fast and concise - thank you.
