### ISSUE TITLE
Make WebRTC/H264 start-up UX a bit smoother

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1263]
Initializing the WebRTC can feel a bit rough, because the stream can flicker once or twice before it’s stable, and the on-screen keyboard can jump around (if shown).

https://user-images.githubusercontent.com/83721279/212946059-93620014-5115-4ef8-9606-d1b254f07507.mov

Maybe it’s possible for us to make the experience a bit smoother? Ideas include:

- Introduce a loading state for the remote screen (e.g., a spinner or so), that also hides the on-screen keyboard while loading.
- Make transition between MJPEG and H.264 so swift that it doesn’t flicker
- Prevent double-flickering, that sometimes occurs, which is probably most confusing

**Comment by mtlynch** [comment]
Do we know what's causing the flicker?

**Comment by mtlynch** [comment]
It's worth digging into further, since it's unexpected. I've added it to the current milestone.
