### ISSUE TITLE
Remove remaining video parameter defaults from `settings.yml` / bundle installer

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1267]
We originally wrote all uStreamer parameters for configuring the video settings into the [now-retired `quick-install` script](https://github.com/tiny-pilot/tinypilot/blob/32da01875dcedc64b533e023bf2861d378c086bf/quick-install#L68-L80) (later migrated as-is to the [bundle installer](https://github.com/tiny-pilot/tinypilot/blob/777eedea375324a8650962c195c105177fe37000/bundler/bundle/install#L83-L96)). The reasoning was that we wanted to selectively run parts of the uStreamer Ansible role in order to update the video settings from the UI. (See https://github.com/tiny-pilot/ansible-role-tinypilot/issues/110 and https://github.com/tiny-pilot/tinypilot/pull/657.)

This is no longer necessary, as we just abandoned the Ansible-based update mechanism of the video settings in favour of the [launcher-based mechanism](https://github.com/tiny-pilot/tinypilot/pull/1252).

In https://github.com/tiny-pilot/tinypilot/issues/1110 / https://github.com/tiny-pilot/tinypilot/pull/1268 we already remove the defaults for tc358743/Voyager hardware.

It should be safe to clean up the [remaining 3 defaults](https://github.com/tiny-pilot/tinypilot/blob/777eedea375324a8650962c195c105177fe37000/bundler/bundle/install#L91-L95) as well, i.e. for non-tc358743 hardware.

Abandoning the video parameters from `settings.yml` altogether means that we are slimming the surface of the settings API, so it’s worth to check whether we are able to simplify other code, e.g. in `ansible-role-tinypilot`.

(Note: [the 2 general uStreamer parameters](https://github.com/tiny-pilot/tinypilot/blob/777eedea375324a8650962c195c105177fe37000/bundler/bundle/install#L67-L68) are maybe not eligible for clean-up, as they are still needed for [server-side wiring](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/70321141a8f90589962f1ae4069002afad355b7b/tasks/nginx.yml#L12). Per [comment below](https://github.com/tiny-pilot/tinypilot/issues/1267#issuecomment-1387253445), we should check this separately, though.)

Follow-up: https://github.com/tiny-pilot/tinypilot/issues/1269.

**Comment by jdeanwallace** [comment]
@jotaen4tinypilot 

> (Note: [the 2 general uStreamer parameters](https://github.com/tiny-pilot/tinypilot/blob/777eedea375324a8650962c195c105177fe37000/bundler/bundle/install#L67-L68) are not eligible for clean-up, as they are still needed for [server-side wiring](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/70321141a8f90589962f1ae4069002afad355b7b/tasks/nginx.yml#L12)!)

Is this correct? We already [set the default `ustreamer_interface` and `ustreamer_port` in `vars/main.yml`](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/70321141a8f90589962f1ae4069002afad355b7b/vars/main.yml#L14-L15) which will then get [saved to `/opt/ustreamer-launcher/configs.d/000-defaults.yml`](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/107df3348724e894cef445f63c1138cc98c97c04/tasks/install_launcher.yml#L67). So does that make it safe to remove?
