### ISSUE TITLE
Buster→Bullseye: Implement frontend for “update requires manual intervention” scenario

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1284]
Part of https://github.com/tiny-pilot/tinypilot-pro/issues/720.

We need to implement the UI [(as proposed)](https://github.com/tiny-pilot/tinypilot-pro/issues/715) for the update scenario that requires manual intervention from the user. The Gatekeeper API structure is defined in https://github.com/tiny-pilot/gatekeeper/issues/129, which this ticket is blocked on.

As noted in the UI proposal, it might make sense to aim for e.g. a modular structure of the [`<update-dialog>` code](https://github.com/tiny-pilot/tinypilot/blob/master/app/templates/custom-elements/update-dialog.html), instead of just adding in a bunch of conditionals. We don’t have to predict future use-cases, but it should overall be clear to see and follow the two possible UI variants in the code (i.e., automated and manual update).

**Comment by mtlynch** [comment]
>Unless mtlynch you have an opinion here, the assignee could just briefly investigate this question and make a call.

Yeah, I'll defer to assignee.
