### ISSUE TITLE
Failed to build `cryptography` on Raspberry Pi OS Lite Buster

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/tinypilot#1299]
TinyPilot is failing to install on Raspberry Pi OS Lite Buster, via the `get-tinypilot.sh` installation script:

### Error
```bash
          Python: 3.7.3
          platform: Linux-5.10.103-v7l+-armv7l-with-debian-10.13
          pip: n/a
          setuptools: 67.2.0
          setuptools_rust: 1.5.2
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================

      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

      This package requires Rust >=1.48.0.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
```

**Comment by jdeanwallace** [comment]
This bug could have been caught by our [old e2e test](https://github.com/tiny-pilot/tinypilot/commit/923d5196a075cad67c0b92b1087ebd5a09633932) 🤔

**Comment by mtlynch** [comment]
D'oh, this just happened https://github.com/tiny-pilot/tinypilot-pro/issues/749

I thought this one was okay since it was outside of the ARM image. Reverting...

**Comment by jdeanwallace** [comment]
@mtlynch - I don't think that's the issue 🤔

**Comment by mtlynch** [comment]
Oh, right. Which version of Community is it trying to install?

838e96541eb1ed9ba1d20ef43bd1205969ea6b5f introduced the error and then 092f0bf65bf23e1df24bdc149818b85121191172 should have fixed it. Is Gatekeeper serving an old copy?

**Comment by jdeanwallace** [comment]
Installing from https://github.com/tiny-pilot/tinypilot/commit/092f0bf65bf23e1df24bdc149818b85121191172 fails for me on device (buster).

Downgrading to `cryptography==37.0.4` here, fixed the issue on device:
https://github.com/tiny-pilot/tinypilot/blob/092f0bf65bf23e1df24bdc149818b85121191172/bundler/bundle/requirements.txt#L10

**Comment by mtlynch** [comment]
Okay, can we downgrade to 37.0.4?
