### ISSUE TITLE
Speed up branch builds / tests on CI

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1342]
One complete CI run (build, test) of a branch takes around 6–7 minutes to complete, most of which is spend building the Ansible role.

<img width="1035" alt="Screenshot 2023-03-28 at 17 24 03" src="https://user-images.githubusercontent.com/83721279/228288267-23995317-3bd7-493e-9826-bd94f395cec3.png">

The delay is not *super* bad, but I often find that this time isn’t really long enough to start something else in the meantime (especially if you want to do the Pro merge afterwards, and thus fully complete a task), yet it’s still long enough to cause some friction sometimes.

I’m wondering whether it’s possible for us to speed up the build process to increase turnover time on branches, without taking away safety. It’s always an option to enable [“auto-merge” on Github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request), but I personally don’t like that as much because I prefer to be in control of what happens.

## Option: CircleCI dynamic configs

One potential option could be to use CircleCI’s dynamic configuration, which would allow us to run jobs based on the files that had been changed. (CircleCI specifically invented this feature to make it easier to work with monorepos.)

- Announcement blog post: https://circleci.com/blog/introducing-dynamic-config-via-setup-workflows/
- Docs: https://circleci.com/docs/dynamic-config/?section=configuration

**Comment by mtlynch** [comment]
Cool, I didn't know CircleCI offered that, but I've wished for something like it. Sounds worth exploring!

I don't want to go too complicated with it, but skipping the Ansible tests if we haven't touched any Ansible files would be worthwhile.
