### ISSUE TITLE
Enhance UX around pasting (sending clipboard content to target device)

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1346]
## Close as Duplicate! (2023-04-03)

This issue was split up:

- https://github.com/tiny-pilot/tinypilot/issues/1137 for the dialog part
- https://github.com/tiny-pilot/tinypilot/issues/1347 for the stored snippets part

---

While looking into [the re-design of the on-screen keyboard](https://github.com/tiny-pilot/tinypilot/issues/1304), I had a few semi-related ideas about the paste feature. Similar to the keyboard, the paste feature is quite old. That in itself is not the reason to do something about, but I rather remember that I found the functionality of the paste overlay a bit surprising and also not really predictable when I used it for the first time. Therefore, I wanted to dump some thoughts about it, just for us to consider whether it would be worthwhile to make changes to it.

## Dialog

What I found quite unintuitive about the paste overlay initially is that it reacts to the keyboard shortcut for pasting (e.g., “Ctrl+V” or “Meta+V”), and then takes action immediately. That way, I don’t get to review what is send to the target machine, and I also don’t have the option to modify the keystroke sequence beforehand.

An alternative approach to this would be to make the paste feature a dialog with a text area. That would allow me to paste, review, and modify my copy, or even to pre-fabricate it then and there from scratch.

![Screenshot 2023-03-31 at 16 07 18](https://user-images.githubusercontent.com/83721279/229148380-b84c7876-33f5-4110-8bae-e6fb0208d4f2.png)

One potential downside is that I’d have to do one extra click after pasting to send the text over. (Which to me wouldn’t be super bad.)

We also need to decide on a good wording and/or help text: it should be clear to the user that we are unable to send text (as in: characters), but we technically send keystrokes – these might result in different characters, depending on the keyboard layouts of the source and target system. So the button label probably shouldn’t be “Send Text”, because that wouldn’t be accurate; however, there might be a better wording than “Send Keystrokes”?

## Stored Snippets

It might be handy for users to be able to build up a library of text snippets that they regularly want to paste and send to their target devices. E.g., their public SSH key, or some URL, etc.

That could be a separate dialog, where users could add and manage these snippets, and then send them over via one click.

<img width="882" alt="Screenshot 2023-03-31 at 16 30 56" src="https://user-images.githubusercontent.com/83721279/229149351-5cb89fef-1f8e-4838-b7c0-600ef570a3d6.png">

This mockup is built directly on the Virtual Media UI, and it probably isn’t the most optimal design for this use-case; it’s just for getting the idea across.

**Comment by mtlynch** [comment]
Oh yeah, this is a million times better than what we have.

Where would you estimate this in terms of [t-shirt sizing](https://github.com/tiny-pilot/tinypilot-pro/wiki/Issue-Labels#size-labels)?
