### ISSUE TITLE
uStreamer Debian package: MEGA-TICKET

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/tinypilot#1353]
This ticket is the result of https://github.com/tiny-pilot/ustreamer-debian/issues/1

# Overview

We want to reimplement `ansible-role-ustreamer` functionality as a Debian package.

# Background

We've found that running Ansible is generally a slow process that might not be well suited for installing TinyPilot and TinyPilot related software, like uStreamer. We've already partially migrated our TinyPilot installation away from Ansible to a Debian package and we'd like to do the same with our uStreamer installation. Using a Debian package speeds up the installation process by using simple bash scripts, as opposed to Python in Ansible, and skipping a package installation when the version requirement has already been met.

# Milestones

### Goal

Avoid building uStreamer on the device, reducing the TinyPilot installation time by about 20s.

This is the highest priority goal because it gives us the most value from migrating uStreamer to a Debian package.

### Steps

- https://github.com/tiny-pilot/ansible-role-ustreamer/issues/99

- https://github.com/tiny-pilot/ustreamer-debian/issues/3

- https://github.com/tiny-pilot/ustreamer-debian/issues/4

- https://github.com/tiny-pilot/ansible-role-ustreamer/issues/100

### Goal

Avoid making parallel changes (i.e., bumping version numbers) in <s>both `ansible-role-ustreamer`, and `ustreamer-debian` repos</s> the `ansible-role-ustreamer` repo; when we later incrementally migrate uStreamer's Ansible role functionality to the Debian package.

### Steps

- https://github.com/tiny-pilot/ansible-role-ustreamer/issues/113

- https://github.com/tiny-pilot/tinypilot/issues/1426

- https://github.com/tiny-pilot/tinypilot/issues/1427

- <s>Archive `ustreamer-debian` repo</s>

- <s>Consolidate `ustreamer-debian` with TinyPilot repo</s>
    - Note from @mtlynch (2023-05-25): We should revisit this, as we might need to keep the two repos separate for license tidiness. ustreamer-debian is GPLv3, whereas tinypilot is MIT, and I'd rather not mix the two licenses within a single repo.

- <s>Bundle local version of uStreamer's Debian package file</s>

### Goal

Migrate highest-impact and/or lowest-effort Ansible tasks to Debian package.

### Steps

- https://github.com/tiny-pilot/tinypilot/issues/1428

- https://github.com/tiny-pilot/ustreamer-debian/issues/11

- https://github.com/tiny-pilot/ustreamer-debian/issues/12

### Goal

Purge uStreamer's Ansible role.

### Steps

- Install `yq` as part of the uStreamer Debian package

  - This is in preparation for migrating the uStreamer launcher script, which depends on `yq`
  - This will help us to parse the `/home/ustreamer/config.yml` file and determine the value of `ustreamer_capture_device` which is needed to [provision the TC358743 chip](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/master/tasks/main.yml#L83-L85) and determine [uStreamer launcher runtime config](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/master/tasks/provision_tc358743.yml#L74-L81)
  - To avoid conflicts with system software, we could install `yq` to `/home/ustreamer/.local/bin`
    - https://unix.stackexchange.com/a/264495

- Migrate [default uStreamer config for TC358743 chips](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/master/tasks/provision_tc358743.yml#L74-L81) to uStreamer's Debian package `postinstall` script

  - This gives us enough info to create the `/opt/ustreamer-launcher/configs.d/000-defaults.yml` file on devices with TC358743 chips

- Migrate [default uStreamer config for non-TC358743 chips](https://github.com/tiny-pilot/tinypilot/blob/master/bundler/bundle/install#L83-L93) to uStreamer's Debian package `postinstall` script

  - This gives us enough info to create the `/opt/ustreamer-launcher/configs.d/000-defaults.yml` file on devices with non-TC358743 chips
  - This isn't strictly required, but it would be nice to consolidate all the default uStreamer launcher config in one place

- Migrate uStreamer launcher script to uStreamer Debian package

  - This requires all dynamically determined uStreamer config (i.e., [default config for TC358743 chips](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/master/tasks/provision_tc358743.yml#L74-L81)) to live within the uStreamer Debian package
  - After this task, all uStreamer's command-line arguments will be consolidated within uStreamer's Debian package

- Migrate the provisioning of the TC358743 chip, which consists of the following sub-tasks:

  - Migrate `/boot/config.txt` to uStreamer Debian package

  - Migrate `/boot/cmdline.txt` to uStreamer Debian package

  - Migrate TC358743 EDID file to uStreamer Debian package

  - Migrate TC358743 EDID loader systemd service to uStreamer Debian package

- Migrate uStreamer Janus plugin config to uStreamer Debian package

  - This depends on the [value of `ustreamer_capture_device`](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/master/templates/janus.plugin.ustreamer.jcfg.j2#L5)

- Migrate uStreamer systemd service to uStreamer Debian package

- Install uStreamer Debian package from TinyPilot's Ansible role

- Purge uStreamer's Ansible role from TinyPilot repo

**Comment by mtlynch** [comment]
@jdeanwallace - Is anything left of this or should we close as complete?
