### ISSUE TITLE
Automatically attempt to reconnect to H.264 stream

### ISSUE THREAD

**Issue by db39** [tiny-pilot/tinypilot#1371]
A [number of users](https://forum.tinypilotkvm.com/-631/audio-video-cuts-out) are having issues with the H.264 stream falling back to MJPEG streaming - causing audio to drop completely on their Voyager 2a.

Usually, the fallback to MJPEG is caused by a temporary network latency spike. Refreshing the web interface restores the H.264 stream, but this is a frustrating process for users who encounter this more frequently.

If H.264 is the currently selected streaming mode, and it fails, is it possible to automatically attempt to reconnect to the H.264 stream?

**Comment by mtlynch** [comment]
Closing, as we're tracking this in #945
