### ISSUE TITLE
Remote screen: implement heights properly, without “jumping”

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1376]
When increasing the viewport size vertically, the height of the remote screen grows, but it performs weird jumps. While growing, it doesn’t keep a consistent margin to the status bar at the bottom.

https://user-images.githubusercontent.com/83721279/234668517-fc57a38b-bbe6-4465-a129-36f76c88b76b.mov

These jumps actually come from our implementation:

https://github.com/tiny-pilot/tinypilot/blob/a65c8192fa8a67f09f7711d47d3d320b05d4a79a/app/templates/custom-elements/remote-screen.html#L11-L33

We introduced these steps/breakpoints in order to solve [an issue where the bottom part of the remote screen could be cut off](https://github.com/tiny-pilot/tinypilot/issues/797). The breakpoint-based solution is pragmatic for fixing this issue, but it’s more of a “heuristic” approach, rather than a proper and robust implementation.

I haven’t tried it out, but I feel quite certain that it should be possible to come up with a “clean” solution that just scales the remote screen height smoothly, while keeping the bottom margin consistent.

Now that we have [made the on-screen keyboard floating/hovering](https://github.com/tiny-pilot/tinypilot/pull/1374), the UI as a whole is not scrollable anymore – I believe might allow us to simplify the page setup CSS-wise, and also solve this issue at the same time.

**Comment by mtlynch** [comment]
Fixed in https://github.com/tiny-pilot/tinypilot/pull/1583
