### ISSUE TITLE
Write updates to disk when there's insufficient RAM for a RAMdisk

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1402]
@pacmac reported that they're unable to install/update TinyPilot on a Pi Zero 2 W:

https://github.com/tiny-pilot/tinypilot/issues/1392#issuecomment-1551244729

The problem is likely that the Zero 2 W [only has 512 MB of RAM](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/).

I would have expected RAMdisk creation to fail, but it looks like RAMdisk creation succeeds, but then the user sees a "No space left on device" error when they exhaust available RAM.

Technically, TinyPilot only supports the Pi 4B, but I'd like to keep installation working on other Pis if it's easy for us to do.

Can we adjust our install/update paths so that we only create a RAMdisk if there's 500m of available RAM, otherwise, we write to `/var/tmp` or somewhere temp location that will auto-delete at some point?

**Comment by pacmac** [comment]
This was an update to an existing install, not a fresh install.

If I do a fresh install, all that was needed was to create a 1GB Swap file, and the install would succeeded.

Thye update still seems to call the same same install script, and during this update it fails with out of disk space error.

**Comment by mtlynch** [comment]
@jdeanwallace - I'd rather not mess with the system's swap settings. I don't think the user would expect TinyPilot to increase swap file size system-wide.

If it's hard to install in `/var/tmp`, maybe a solution is to prompt the user like "Can we increase your swap size to 500 MB?" but I'm hoping it will be pretty easy to just silently install to `/var/tmp` when there's not enough RAM available.

**Comment by pacmac** [comment]
The zero 2W makes a very compact tool that you can easily put in your pocket.

I have the wpa_supplicant simlinked on the /boot partition so I can always plug the card into a laptop and set the SSID & password.

But I have been considering using hostapd where the device would become an access point if it was unable to connect to a network. It would be nice to see that added as a feature to tinypilot :-)

I also reduced the GPU ram from 256m to 128 and it seems to be fine.

![IMG_6332 Large](https://github.com/tiny-pilot/tinypilot/assets/2349856/1bf7eeb3-37f6-4c40-95e4-151e10a7747d)
![IMG_6333 Large](https://github.com/tiny-pilot/tinypilot/assets/2349856/6b4599d6-3f5e-4a53-a2ba-6a78a5f900bc)

**Comment by mtlynch** [comment]
Nice, that looks like a cool, compact device!

>But I have been considering using hostapd and creating a Captive Portal where the device would become an access point if it was unable to connect to a network, and allow the user to connect to it, and select a SSID & password - It would be nice to see that added as a feature to tinypilot :-)

Yes, agreed. I want to start with a tutorial showing how to do it manually and then implement it as a first-class feature if there's enough interest.

@bderenzo created a [tutorial](https://github.com/tiny-pilot/tinypilot/issues/92#issuecomment-683112906) in the early days of TinyPilot, so I'm not sure if it would still work. I recently set up my TinyPilot as a WiFi AP based on these steps:

https://blog.thewalr.us/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/
