### ISSUE TITLE
Migrate uStreamer directory permissions to the uStreamer Debian package

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/tinypilot#1467]
~~Blocked on https://github.com/tiny-pilot/tinypilot-pro/issues/975~~

Related https://github.com/tiny-pilot/tinypilot/issues/1353

Set the correct permissions of the uStreamer directory (i.e., `/opt/ustreamer`) using the uStreamer Debian package, instead of [using Ansible](https://github.com/tiny-pilot/tinypilot/blob/bc069bd50026216fc0260e215dadfca8eb5fa7ed/ansible-role-ustreamer/tasks/main.yml#L172-L180).

Follow these steps to implement the change and verify that it works as expected:

1. (For background) Read the first half of the [Ansible-to-Debian refactoring doc](https://github.com/tiny-pilot/tinypilot-pro/blob/master/ANSIBLE.md) (until the section "Testing your changes")
1. In the uStreamer Ansible role, delete the ["fix uStreamer folder permissions"](https://github.com/tiny-pilot/tinypilot/blob/34918d7ed87e401fb633c7697ab8702e9702b21d/ansible-role-ustreamer/tasks/main.yml#L30-L38) Ansible task.
1. In the [uStreamer Debian package](https://github.com/tiny-pilot/ustreamer-debian), add a step to the `postinst` script that assigns ownership of the uStreamer directory (i.e., `/opt/tinypilot`) to the `ustreamer` user and group (similar to [what we do in the TinyPilot Debian package](https://github.com/tiny-pilot/tinypilot/blob/34918d7ed87e401fb633c7697ab8702e9702b21d/debian-pkg/debian/tinypilot.postinst#L31)).
1. [Build a new uStreamer Debian package](https://github.com/tiny-pilot/tinypilot-pro/blob/master/CONTRIBUTING.md#build-a-ustreamer-debian-package), with your changes, on CircleCI.
1. In the uStreamer Ansible role, change the [`ustreamer_debian_package_path`](https://github.com/tiny-pilot/tinypilot/blob/34918d7ed87e401fb633c7697ab8702e9702b21d/ansible-role-ustreamer/vars/main.yml#L3) to the CircleCI artifact of your uStreamer Debian package with a comment saying it's for temporary testing.
1. [Build a one-off TinyPilot Community install bundle](https://github.com/tiny-pilot/tinypilot-pro/blob/master/CONTRIBUTING.md#installing-a-tinypilot-bundle) with your changes.
1. Install the bundle on a bare Raspbian system.
1. Verify that files in `/opt/ustreamer` are owned by `ustreamer` and have group `ustreamer`.
1. Create a PR for your uStreamer Debian package changes.
1. After the PR is reviewed and merged, request that Michael cut a new uStreamer Debian package release.
1. In the uStreamer Ansible role, update the [`ustreamer_debian_package_path`](https://github.com/tiny-pilot/tinypilot/blob/34918d7ed87e401fb633c7697ab8702e9702b21d/ansible-role-ustreamer/vars/main.yml#L3) to be the URL of the newly released uStreamer Debian package that contains your changes.
1. Create a draft PR from your TinyPilot repo changes.
1. Add [test instructions to your draft PR](https://github.com/tiny-pilot/tinypilot-pro/blob/master/ANSIBLE.md#include-testing-instructions-for-your-reviewer) that allows a teammate to easily test your changes 
1. Submit your PR for review.
1. After the PR is approved, perform the [pre-merge tests](https://github.com/tiny-pilot/tinypilot-pro/blob/master/ANSIBLE.md#before-merging-your-pr) on your TinyPilot repo changes.
1. Merge your PR.

**Comment by mtlynch** [comment]
@db39 - Can you take this on before taking on any new tasks? We've got some Ansible-to-Debian tasks that we need before completing some of the dev work for 2.6.1, so I'd like to prioritize this one, as it will help us test the process of support eng working on this end-to-end.

This is a newly documented process. The dev team has been following kind of ad-hoc processes to do this work for the past year, but we wanted to formalize it more so that the support eng team can participate.

If there are things that are confusing, it's likely a gap in the documentation, so definitely ask about things that don't make sense or places where you get stuck.

**Comment by db39** [comment]
@mtlynch - Sure!

**Comment by mtlynch** [comment]
We can just repeat the same thing we did in the other script and update the bug to say we're doing it in both places.

**Comment by db39** [comment]
Ok, cool! Is there a way to ignore the warning that breaks the build, or do I have to remove the `lintian` task?

**Comment by mtlynch** [comment]
We should add a `.lintianignore` line like this:

https://github.com/tiny-pilot/tinypilot/blob/0ef51cafd5d7091f272fc12218982dd9097d72dc/.lintianignore#L13-L15

**Comment by mtlynch** [comment]
@db39 - For unexpected CI runs, it's helpful if you can link to the specific run + commit. I think you're talking about this one?

https://github.com/tiny-pilot/tinypilot/commit/11af204a2c8de6f242333e2221805b432646be0c
https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3786/workflows/b8933ada-5abe-4a70-ae1e-f68949336fb8

@jdeanwallace - Can you update the instructions? It seems like at the very least `default` should be backticked so the reader knows we mean that specific YAML key.

**Comment by db39** [comment]
@mtlynch, @jdeanwallace - Thanks for the info! 

I realized my mistake with the `base-revision` param and fixed it in the following commit: https://github.com/tiny-pilot/tinypilot/commit/b4cc5e46a2d8e25bd6e60cb0d4b1384e411dc3f. It still didn't build a bundle on [this workflow](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3787/workflows/a11a3abb-eccb-41f2-865f-813acd23f0e0).

**Comment by jdeanwallace** [comment]
@db39 - Oh, it look like it did build:

Your change: https://github.com/tiny-pilot/tinypilot/commit/b4cc5e46a2d8e25bd6e60cb0d4b1384e411dc3f
Your workflow with a bundle: https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3793/workflows/ae32e331-2005-4701-b5b1-227806788be0

**Comment by db39** [comment]
@jdeanwallace - yeah that workflow is the one where I used the custom param + manual trigger earlier today.

**Comment by jdeanwallace** [comment]
@db39 - Oh right, I see the time difference now.
