### ISSUE TITLE
Add method of adding a custom nginx SSL certificate

### ISSUE THREAD

**Issue by LordAro** [tiny-pilot/tinypilot#1485]
At my org we have a wildcard *.example.com certificate that we use for all server machines. I'd quite like to use this on the tinypilots as well to avoid the self-signed certificate errors.

Is there a good way of setting `ssl_certificate` & `ssl_certificate_key` nginx variables ? I've trawled through the various source files but I can't find anything. I can set `tinypilot_manage_tls_keys` in settings.yml, but that only gets rid of the self-signed certs, it'd be good to have a "proper" way of inserting my own.

In the past I've managed to hack this in by overriding some ansible variables, but since you seem to be moving away from ansible (#1429) I'm not quite sure of a way to do this anymore in 2.5.0 or 2.6.0

(I upload the certs to the tinypilot via my own ansible roles, ironically enough)

**Comment by mtlynch** [comment]
If you add the line `tinypilot_manage_tls_keys: no`, then TinyPilot's installer will stop managing nginx's TLS keys. In other words, if you overwrite the TLS keypair with your own, we'll preserve it on each update.

We're in the process of writing official instructions for this. They're not fully edited yet, but they're at the point where it should be easy to follow:

https://64909c689ea3321e09d1a5d8--tinypilot.netlify.app/faq/own-tls-key

Let me know if you have any questions about getting this working or if there's anything you'd like to see in the docs when we publish them.
