### ISSUE TITLE
Improve CPU throttle lines in TinyPilot logs

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1489]
The CPU throttle line is currently inconsistent with most other lines in the TinyPilot logs.

We should clean it up to be more user-friendly and consistent with our other lines.

### Current

```text
throttled=0x0
```

### Desired

```text
CPU throttled since boot: No
```

**Comment by jdeanwallace** [comment]
While reviewing https://github.com/tiny-pilot/tinypilot/pull/1543, I noticed that the current style of the logs is for the text after the colon to be lowercase. For example:

```
TinyPilot state
Read-only filesystem: off
SSH access: enabled
Mouse jiggler: disabled
```

So in this case, should we use a lowercase "yes"/"no"?

**Comment by mtlynch** [comment]
Yeah, that's true. We should stick to lowercase.
