### ISSUE TITLE
Define separation of configuration in `~/settings.yml` and the SQlite DB

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1524]
We will reach an de-Ansibilized state in the foreseeable future. One “relict” or by-product is the YAML-based config file, `/home/tinypilot/settings.yml`, which still contains important config parameters that we rely on (independent of Ansible).

However, we also have the SQlite database, which contains configuration logic as well – such as whether H.264 or MJPEG is enabled, or whether HTTPS should be required.

I think the current/previous division of concerns was “by consumer”:

- If configuration is consumed by Ansible at install/update time, then it lives in `~/settings.yml`
- If configuration is managed by the Python app at “runtime”, then it lives in the SQlite

We should clearly define where things are supposed to go and how our configuration is structured. The SQlite and the `~/settings.yml` also have different practical constraints, which we should be aware of – e.g. the SQlite has a more powerful structure, but it cannot easily be processed outside of the Python app.

**Comment by mtlynch** [comment]
Just to clarify, I didn't mean my opinion as an edict. I'm open to other solutions if we want a different strategy.

>I feel if we’d effectively “deprecate” settings.yml (or at least declare it exceptional), we should consider looking into a robust mechanism for reading from tinypilot.db programmatically, to promote its usage over reading from settings.yml in the future. For instance, if I were to implement the configure-janus privileged script by gating it on tinypilot.db instead of settings.yml, I currently wouldn’t know how to do that best.

Yeah, that's a good idea. Can you create ticket for that?

It seems like there should be some way of making the Flask CLI faster because what the heck is it doing for several seconds just to do a single SQLite database call?
