### ISSUE TITLE
Upgrade all Python dev dependencies

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1533]
We recently upgraded our Python/pip production dependencies via https://github.com/tiny-pilot/tinypilot-pro/issues/1002.

We can’t trivially upgrade our [dev dependencies](https://github.com/tiny-pilot/tinypilot/blob/master/dev_requirements.txt) `isort`, `pylint`, and `sqlfluff` to their latest respective versions. It seems that those are not backwards-compatible (at least they don’t work out of the box) and would require code or configuration changes on our end for them to work again.

So we should look into this separately and more closely.

**Comment by mtlynch** [comment]
Can you share more details about what's stopping us from upgrading? Do you mean like isort would choose different sorting, so it would cause code churn?

**Comment by mtlynch** [comment]
Let's revisit this if we have a need for something in a later dev package release.

For a dev team of our size, I think keeping up with breaking changes in dev packages isn't really worth the cost when we're satisfied with the versions we have.

For libraries we're using in production, there's more of a reason to keep things up to date (e.g., security issues, subtle bugs users might be hitting in the field), but for dev packages, there's not as much value, and there's a definite cost to the churn.
