### ISSUE TITLE
Unable to trigger bundle builds for all commits on a feature branch

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/tinypilot#1548]
As @db39 [discovered](https://github.com/tiny-pilot/tinypilot/issues/1467#issuecomment-1662242781), the [first described method of triggering a bundle build](https://github.com/tiny-pilot/tinypilot/blob/0ef51cafd5d7091f272fc12218982dd9097d72dc/CONTRIBUTING.md#installing-a-nightly-bundle) doesn't work anymore:

> 1. Temporarily enable bundle builds for all commits on a feature branch:
>    1. In [the CircleCI configuration](/.circleci/config.yml), change the `bundle_build_branch` parameter’s default value from `master` to `<< pipeline.git.branch >>`.
>    1. Push your changes as branch to GitHub. CircleCI will now automatically build bundles for all subsequent commits of that branch.
>    1. Before eventually merging your feature branch, remember to revert the `bundle_build_branch` parameter to the original value (i.e., `master`).

Luckily we can still manually trigger a bundle build via the CircleCI dashboard (i.e., [the second described method](https://github.com/tiny-pilot/tinypilot/blob/0ef51cafd5d7091f272fc12218982dd9097d72dc/CONTRIBUTING.md#installing-a-nightly-bundle)).

We should either fix this or remove it as an option if manually triggering a bundle build via the CircleCI dashboard is good enough.

**Comment by mtlynch** [comment]
Any idea what broke this?

It seems useful to have the code-based way. If you're doing work focused on the bundle, it's probably annoying to have to keep retriggering the workflow manually.

**Comment by jdeanwallace** [comment]
I think it's a regression since https://github.com/tiny-pilot/tinypilot/pull/1518

**Comment by jdeanwallace** [comment]
> I think it's a regression since #1518

Confirmed.
* Before https://github.com/tiny-pilot/tinypilot/commit/9ccaa2a88e1965513a13c75c12e8f409aca0be42 ([working](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3842/workflows/3852de5f-308e-4e41-8931-0478f3c21e1c))
* After https://github.com/tiny-pilot/tinypilot/commit/54dcf2fbddb9fd37a6eceb14c99a88e785ca9db2 ([not working](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/3843/workflows/fd121bf0-e3ad-437d-a9d9-64bf505f1f17))
