### ISSUE TITLE
Move internal ports to less-frequently-used port numbers

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1551]
TinyPilot has three ports

* `8000`: TinyPilot web app
* `8001`: uStreamer
* `8002`: Janus

It used to be possible for users to override these variables, but TinyPilot Pro 2.6.1 is adjusting how we handle these variables so they're not longer user-configurable.

Since the ports we're currently using are popular with other applications, we should move to ports less likely to collide with other apps:

### Desired ports

* `48000`: TinyPilot web app
* `48001`: uStreamer
* `48002`: Janus

**Comment by jdeanwallace** [comment]
@mtlynch - We didn't have an explicit bug for it, but I did attempt to implement this as part of https://github.com/tiny-pilot/tinypilot/issues/1429

* https://github.com/tiny-pilot/tinypilot/pull/1479
