### ISSUE TITLE
Make app agnostic of `$HOME` environment variable

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1571]
There are several places in the app where we rely on the `~` path shortcut, or the `$HOME` environment variable respectively. For example when [processing the `settings.yml` file](https://github.com/tiny-pilot/tinypilot/blob/master/app/update/settings.py#L21).

Usually, the app is run under the `tinypilot` system user. There are two exceptions for this, however:

- When installing tinypilot on a clean device, the installation is executed under a different user, e.g. `root`.
- When running commands with `sudo` (e.g., privileged scripts, or other manual scripts), the `$HOME` environment variable is set to be `/root`. This is because [the default sudoers file contains the `env_reset` directive](https://www.sudo.ws/docs/man/1.8.32/sudoers.man/#:~:text=By%20default%2C%20the%20env_reset%20flag%20is%20enabled.).

In either of those two scenarios, the app won’t pick up files and data from the `tinypilot`’s home directory, e.g. `settings.yml`, or the SQlite DB.

## Example Cause
The `postinstall` Debian script [executes the `render-template` script](https://github.com/tiny-pilot/tinypilot/blob/b9d60675e8bbf0d112614d8d48e328267cf80fd7/debian-pkg/debian/tinypilot.postinst#L66), which internally uses the `update` Python module. In `update/settings.py`, however, [we expand the `~` user](https://github.com/tiny-pilot/tinypilot/blob/master/app/update/settings.py#L21). So if the Debian package was installed as user `root`, then `~` expands to `/root`. Therefore, `render-template` looks at `/root/settings.yml`, and since that file doesn’t exist, it [continues with the default settings](https://github.com/tiny-pilot/tinypilot/blob/b9d60675e8bbf0d112614d8d48e328267cf80fd7/app/update/settings.py#L101-L102).

## Possible Solution
The naive solution would be to replace `~` with `/home/tinypilot`. While we are on it, we should double-check whether there are other places that rely on the “relative” `~` user.

**Comment by mtlynch** [comment]
Hardcoding to `/home/tinypilot` sounds good.

**Comment by jdeanwallace** [comment]
As an alternative to both:
* https://github.com/tiny-pilot/tinypilot/issues/1571#issuecomment-1681071113
    > Hardcoding to /home/tinypilot sounds good.
* https://github.com/tiny-pilot/tinypilot/pull/1572

Could we assume that tinypilot is always run by the correct user (i.e., `tinypilot`) and alter the way we the Debian `postinst` script [executes the render-template script](https://github.com/tiny-pilot/tinypilot/blob/b9d60675e8bbf0d112614d8d48e328267cf80fd7/debian-pkg/debian/tinypilot.postinst#L66)? 

Something like:

```diff
-. venv/bin/activate && \
+su - tinypilot && \
+  . venv/bin/activate && \
   <<< "${SETTINGS_TEMPLATE}" \
   > "${TINYPILOT_APP_SETTINGS}"
```

This would also keep our current local development environment working as-is.

**Comment by mtlynch** [comment]
Yeah, I think hardcoding is the more robust fix. If we `sudo su tinypilot`, I worry that we're going to keep forgetting to do that or failing to identify places where the active user changes the path.

I think historically, we've made TinyPilot too configurable/dynamic and we can achieve some wins now by scaling back that configurability into mechanisms that are simple and easy to reason about.

**Comment by jdeanwallace** [comment]
Okay cool, thanks for the explanations.
