### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by advanxer** [tiny-pilot/tinypilot#1597]
I am receiving above error when executing the installer. Below is some of the terminal output:
      : 
      creating build
      creating build/lib
      creating build/lib/ansible_collections
      creating build/lib/ansible_collections/amazon
      creating build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/.gitignore -> build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/CHANGELOG.rst -> build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/CONTRIBUTING.md -> build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/COPYING -> build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/FILES.json -> build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/MANIFEST.json -> build/lib/ansible_collections/amazon/aws
      copying ansible_collections/amazon/aws/README.md -> build/lib/ansible_collections/amazon/aws
      :
      : 
      copying ansible_collections/fortinet/fortios/plugins/modules/fortios_system_affinity_interrupt.py -> build/lib/ansible_collections/fortinet/fortios/plugins/modules
      copying ansible_collections/fortinet/fortios/plugins/modules/fortios_system_affinity_packet_redistribution.py -> build/lib/ansible_collections/fortinet/fortios/plugins/modules
      copying ansible_collections/fortinet/fortios/plugins/modules/fortios_system_alarm.py -> build/lib/ansible_collections/fortinet/fortios/plugins/modules
      error: could not write to 'build/lib/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_alarm.py': No space left on device
      [end of output]

I am not sure why the scirpt is copying bunch of plugins which i think it is not related to tinypilot (aws, fortinet, podman, zabbix etc)

below is my hardware and software spec:
Rpi4 2GB
64GB Card
DietPi OS - based on debian bookworm

root@DietPi:~# df -kh
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        57G  1.1G   54G   2% /
devtmpfs        916M     0  916M   0% /dev
tmpfs           950M     0  950M   0% /dev/shm
tmpfs           380M  5.1M  375M   2% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.0G   16K  1.0G   1% /tmp
tmpfs            50M  4.0K   50M   1% /var/log
/dev/mmcblk0p1  127M   33M   95M  26% /boot

root@DietPi:~# free -m
               total        used        free      shared  buff/cache   available
Mem:            1899          80        1725           5         125        1818
Swap:            148           0         148

Any advise will be much appreciated

**Comment by mtlynch** [comment]
Thanks for reporting this!

It looks like you're running DietPi on Debian Bookworm. The only supported OS at the moment is Raspberry Pi OS Lite (Bullseye) 32-bit.

If you're interested in tinkering with TinyPilot on other OSes, there's a thread for exploring them here:

https://github.com/tiny-pilot/tinypilot/discussions/755
