### ISSUE TITLE
No keyboard, no mouse working

### ISSUE THREAD

**Issue by pierreact** [tiny-pilot/tinypilot#1620]
## Description

Hello,

I've installed tinypilot on a raspberry pi 3, everything works but keyboard and mouse.

```
# echo asdf | /root/hid_gadget_test/hid_gadget_test /dev/hidg0 keyboard
	keyboard options:
		--hold
		--left-ctrl
		--right-ctrl
		--left-shift
		--right-shift
		--left-alt
		--right-alt
		--left-meta
		--right-meta

	keyboard values:
		[a-z] or
		--return		--esc
		--bckspc		--tab
		--spacebar		--caps-lock
		--f1    		--f2
		--f3    		--f4
		--f5    		--f6
		--f7    		--f8
		--f9    		--f10
		--f11   		--f12
		--insert		--home
		--pageup		--del
		--end   		--pagedown
		--right 		--left
		--down  		--kp-enter
		--up    		--num-lock

/dev/hidg0: Cannot send after transport endpoint shutdown
````

```
# modprobe g_hid
modprobe: ERROR: could not insert 'g_hid': No such device
```

## What's the behavior that you expect?

Keyboard and mouse to work

## What's happening instead?

What described above.

## What are the steps to reproduce this behavior?

1. Install raspbian bullseye
2. Install tinypilot
3. Connect cables to a compter to be managed (Tried a PC and a mac on different USB cables)

Thank you!

**Comment by mtlynch** [comment]
Thanks for reporting this!

Unfortunately, TinyPilot is not compatible with the Pi 3. See https://github.com/tiny-pilot/tinypilot/issues/911#issuecomment-1040720968 for additional details.

I'm surprised you were able to install, as the installer is supposed to error out if it detects a Pi 3. How did you install TinyPilot?

Can you share the output of this command `cat /proc/cpuinfo`?

**Comment by mtlynch** [comment]
@pierreact - That's strange. The installer should have caught this.

Did you install with the `get-tinypilot.sh` script or some other way?

**Comment by UmutAlihan** [comment]
I am also able to install tinypilot using "get-tinypilot.sh" into my RPI 3 

But I see that unfortunately RPI 3 models don't have proper I/O for OTG , therefore it is not possible to emulate keyboard and mouse in anyway. 

It would be much appreciated if we could somehow solve this mouse/keyboard forwarding with a workaround or another approach.

Many thanks for this great contribution regarding tinypilot overall <3 !!

**Comment by mtlynch** [comment]
@UmutAlihan - Thanks for the kind words.

Unfortunately, I don't think there's any feasible workaround on the Pi 3. If the hardware doesn't support it, there's not much we can do from the software.
