### ISSUE TITLE
`execute_test.py` producing error output during tests

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1642]
In `execute_test.py`, there are two test cases which are producing error output while running, without making the tests fail, though:

- ~[`test_process_with_result_child_exception`](https://github.com/tiny-pilot/tinypilot/blob/cd3f5ff30a04659a750aec6dbf60ca49927f10f0/app/execute_test.py#L58-L71)~
- [`test_execute_with_timeout_child_exception`](https://github.com/tiny-pilot/tinypilot/blob/cd3f5ff30a04659a750aec6dbf60ca49927f10f0/app/execute_test.py#L91-L94)
- [`test_background_thread_ignores_function_exception`](https://github.com/tiny-pilot/tinypilot/blob/cd3f5ff30a04659a750aec6dbf60ca49927f10f0/app/execute_test.py#L99-L100)

Both tests are concerned with handling exceptions from the child process.

This might not be an actual bug, due to [this note](https://github.com/tiny-pilot/tinypilot/blob/cd3f5ff30a04659a750aec6dbf60ca49927f10f0/app/execute_test.py#L59-L61), but I’m not sure about it. If it isn’t a bug, we could maybe check whether we are able to reliably suppress the stack trace printing during the tests.

This is happening on the master branch, but I can also reproduce it locally. The logs snippet below is from the master branch, [see here for the full build](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/4182/workflows/905681f5-0d16-471f-a785-5b12b1c017e4/jobs/28158).

```
+ coverage run --source app --omit '*_test.py' --module unittest discover --pattern '*_test.py' app.log
.........................Exception in thread Thread-1:
.Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.9.17/lib/python3.9/threading.py", line 980, in _bootstrap_inner
.    self.run()
  File "/home/circleci/.pyenv/versions/3.9.17/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/circleci/project/app/execute_test.py", line 31, in raise_exception
    raise Exception('Child exception')
Exception: Child exception
.Process ProcessWithResult-2:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.9.17/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/circleci/project/app/execute.py", line 37, in run
    result.return_value = self._target(*self._args, **self._kwargs)
  File "/home/circleci/project/app/execute_test.py", line 31, in raise_exception
    raise Exception('Child exception')
Exception: Child exception
...........................................................................................................................................................
----------------------------------------------------------------------
Ran 183 tests in 0.802s
```

**Comment by mtlynch** [comment]
Yeah, it's intentional, but we should look into cleaning it up because it does make the output confusing.
