### ISSUE TITLE
Fail install early on Raspbian Bookworm

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1667]
Related https://github.com/tiny-pilot/tinypilot-pro/issues/1113

In testing, we've found that some of TinyPilot's dependencies don't yet work for Raspbian Bookworm.

We should bail the install early with a clear error message to prevent users from trying to install TinyPilot on Bookworm and then being surprised when things break later on.

We have an established precedent for Raspbian version checks here:

https://github.com/tiny-pilot/tinypilot/blob/951b9bfdd51dc856f8c2d8318c6d1859744d00dc/bundler/bundle/install#L21-L31

**Comment by cghague** [comment]
@mtlynch - Would the preference be for two separate checks (i.e., fail on Buster and older, plus fail on Bookworm and newer), or for a single check (i.e., fail on anything that's not Bullseye)?

**Comment by mtlynch** [comment]
Let's do two separate checks because there are two different error messages. If it's 11, we should print the message we already have. If it's >12, we should say that we're not yet compatible with Bookworm, but we're working on it. We should print this bug in the error output so that users can track our progress:

https://github.com/tiny-pilot/tinypilot/issues/1668
