### ISSUE TITLE
Hostname scripts are incompatible with Raspberry Pi OS Bookworm

### ISSUE THREAD

**Issue by cghague** [tiny-pilot/tinypilot#1679]
Related https://github.com/tiny-pilot/tinypilot/issues/1668

Our [hostname scripts](https://github.com/tiny-pilot/tinypilot/tree/master/debian-pkg/opt/tinypilot-privileged/scripts) make changes to `/etc/hostname` directly, which is no longer sufficient nor supported on Raspberry Pi OS Bookworm. We should instead use the `hostnamectl` tool, or we could call the [`do_hostname()`](https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L649) function in `raspi-config`.

**Comment by mtlynch** [comment]
I'd like to go with `hostnamectl` if possible. `raspi-config` doesn't seem like they build with the expectation of third-parties depending on them.
