### ISSUE TITLE
I just want to wirelessly send keystrokes to my Windows from terminal/SSH.

### ISSUE THREAD

**Issue by Kzitold** [tiny-pilot/tinypilot#1697]
Let's say I'm remote computing. I got a VPN'ed Pi to etherwake my desktop since my desktop's VPN apparently sleeps on sleep.
But once my desktop is on the login screen, how would I send keystrokes to `desktop@ip.add.res.s` from terminal/SSH. Like, I want the full wake-up on 1 SSH-macro.

**Comment by mtlynch** [comment]
Thanks for reaching out!

This wouldn't fall in the scope of TinyPilot, but you could probably write a simple bash script to do this. I showed something similar in this blog post:

https://mtlynch.io/key-mime-pi/#usb-device-emulation
