### ISSUE TITLE
ATX power control and status via RS232

### ISSUE THREAD

**Issue by binooetomo** [tiny-pilot/tinypilot#1698]
Dear All.

There is video on how to expanding KVM to multiple Computer.
So I'm pretty sure that tinypilot have no problem at it.

But i didn't find any how to do ATX control for multiple computer.

I think it'll better if tiny pilot have such feature.
My Idea is that tiny pilot 'broadcast' a command via Raspi RS232 GPIO.
Lets say the message is composed of 'address' and 'command'. 

User can build a simple arduino based to listen to all message, and do the job if the address is match to it's own address.
The baudrate of this protocol can be set as low as possible, since the message payload will very short.
The network topology could be a daisy-chain network just like RS485.

sincerely   
-bino-

**Comment by mtlynch** [comment]
Thanks for reaching out!

This isn't something we're currently working on, but we're happy to help community members who want to implement this. The canonical ticket for this feature is #80, so I'm going to close this one as a duplicate.
