### ISSUE TITLE
Consolidate naming and responsibility of dev scripts

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1716]
The [`build-python`](https://github.com/tiny-pilot/tinypilot/blob/master/dev-scripts/build-python) and [`build-javascript`](https://github.com/tiny-pilot/tinypilot/blob/master/dev-scripts/build-javascript) dev scripts technically don’t build anything, but they rather execute tests and static analysis procedures. Therefore, the prefix `build-` might be a bit surprising. To me, “build” would indicate that something is compiled or assembled. I’d probably find `test-` more intuitive here.

We also have several separate “check”-prefixed bash scripts that do static analysis. So it might not be totally clear where to put things. E.g., [Python style checking is performed via `build-python`](https://github.com/tiny-pilot/tinypilot/blob/8e99d5a666df12d851b14dd4276e8b95ab958493/dev-scripts/build-python#L44-L52), whereas [JavaScript style checking is performed via `check-style`](https://github.com/tiny-pilot/tinypilot/blob/8e99d5a666df12d851b14dd4276e8b95ab958493/dev-scripts/check-style#L19-L23) and not via `build-javascript`. As we are [about to add tests for bash scripts](https://github.com/tiny-pilot/tinypilot/issues/1714), we will be having the same duality with [`check-bash`](https://github.com/tiny-pilot/tinypilot/blob/8e99d5a666df12d851b14dd4276e8b95ab958493/dev-scripts/check-bash) and [`build-bash`](https://github.com/tiny-pilot/tinypilot/pull/1721/files#diff-c14d96150976d6dd82312f7b60f78f6b0e89b95de563bf688d5185b2660f6399).

Seeing that we have 20 dev scripts by now, I suggest we take a step back and review their structure altogether, and try to find a more consistent naming and responsibility scheme.

**Comment by mtlynch** [comment]
Yeah, the naming is not super well-thought-out. It's mainly that the scripts match conventions I use in previous projects, and I'm used to the naming at this point, so I don't re-evaluate.

I agree that it's confusing because there's not a clear pattern on when to use `build` vs `check` vs `lint`.

I think we should come up with a small, simple set of rules that we feel comfortable following and adapting our scripts to match.

**Comment by jdeanwallace** [comment]
@jotaen4tinypilot - These changes look good to me.

> Move the enable-passwordless-sudo and the 2 install- scripts to a new folder dev-scripts/remote/, to make it clear that they are supposed to run on device (in contrast to all other scripts, which are made to run on the dev machine)

(nit) The word "remote" makes me think of a device not in my local network. Alternative suggestion: "device"?
