### ISSUE TITLE
Fix dialog initialization process

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1770]
https://github.com/tiny-pilot/tinypilot/pull/1764 introduced a regression: the paste dialog’s `<textarea>` doesn’t receive focus anymore when opening the dialog. This is due to us [switching the dialog initialization order](https://github.com/tiny-pilot/tinypilot/pull/1764/commits/befca18743bddc4ace9d0a3963a5d7fd4879fc3f) in order to fix another problem, which is that you may see [undesired UI animation artifacts](https://codeapprove.com/pr/tiny-pilot/tinypilot/1764#thread-5e35ba98-cc66-47e0-9654-00f9759da3d3) while opening the dialog.

The root cause is that calling `show()` **after** `initialize()` renders the [`this._elements.pasteArea.focus();` call](https://github.com/tiny-pilot/tinypilot/blob/9cdb7dd5e1e5c76dc7f62aaa421d5bb35219edb0/app/templates/custom-elements/paste-dialog.html#L125) irrelevant, because [`show` also implicitly sets focus via calling `showModal()`](https://github.com/tiny-pilot/tinypilot/blob/9cdb7dd5e1e5c76dc7f62aaa421d5bb35219edb0/app/templates/custom-elements/overlay-panel.html#L115).

So right now, we’d have to decide between two problems:

1. Call `.show()` before `.initialize()`: users may see the animation artifact
1. Call `.initialize()` before `.show()`: the `<textarea>` doesn’t receive focus

Note: [`show()` is inherited from the overlay panel](https://github.com/tiny-pilot/tinypilot/blob/9cdb7dd5e1e5c76dc7f62aaa421d5bb35219edb0/app/templates/custom-elements/overlay-panel.html#L113), whereas [`initialize()` is a method from the respective dialog, e.g. in `<paste-dialog>`](https://github.com/tiny-pilot/tinypilot/blob/9cdb7dd5e1e5c76dc7f62aaa421d5bb35219edb0/app/templates/custom-elements/paste-dialog.html#L121).

I’d see two options:

- (1) We could revert [the offending commit](https://github.com/tiny-pilot/tinypilot/pull/1764/commits/befca18743bddc4ace9d0a3963a5d7fd4879fc3f), because I think the focus problem is worse than the animation artifact problem. We’d have to leave an additional comment, however, since this issue is too subtle otherwise.
- (2) We take this opportunity and refactor the initialization process of dialogs in general, so that it is unified across all dialogs, and robust against such kind of issues.

## Considerations on general refactoring of dialog initialization

The [initialization process is basically the same in all our dialogs](https://github.com/tiny-pilot/tinypilot/blob/9cdb7dd5e1e5c76dc7f62aaa421d5bb35219edb0/app/static/js/app.js#L309-L347):

1. We trigger one operation to initialize the dialog. We don’t always have a method called `.initialize()`, but that’s just an accidental inconsistency.
2. We call `.show()`

It makes sense for these two things to occur in the stated order.

Considering the amount of dialogs we have, and that they all essentially work in the same way, we could consolidate the flow, and encode a unified initialization process in the code. For example (just to illustrate the idea):

- `show()` could dispatch two custom events into the dialog component:
  - `dialog-requested`: the dialog may listen to that event, to carry out it’s general init procedure (if applicable)
  - `dialog-shown`: the dialog may listen to that event and do final adjustments, e.g. for setting focus (if applicable)

**Comment by mtlynch** [comment]
>I’d see two options:
>
>1. We could revert [the offending commit](https://github.com/tiny-pilot/tinypilot/pull/1764/commits/befca18743bddc4ace9d0a3963a5d7fd4879fc3f), because I think the focus problem is worse than the animation artifact problem. We’d have to leave an additional comment, however, since this issue is too subtle otherwise.
>1. We take this opportunity and refactor the initialization process of dialogs in general, so that it is unified across all dialogs, and robust against such kind of issues.

Can you share the cost estimate (in t-shirt sizing) of (2)?

**Comment by jdeanwallace** [comment]
Nice catch @jotaen4tinypilot! To make option (1) more appealing, since we've [persisted the last masked state](https://github.com/tiny-pilot/tinypilot/pull/1765) the original animation artifact will no longer be present/noticeable. Yay? 🥲

**Comment by mtlynch** [comment]
Let's do (1) now and hold off on (2).
