### ISSUE TITLE
Build network status dialog for reviewing connectivity info

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1814]
Originated in https://github.com/tiny-pilot/tinypilot/issues/131 (subtask (f)).

We originally wanted to add an indicator to the main UI (e.g., to the status bar), but after discussing options below, we eventually decided to add a new dialog for the user to review the network status. The information we want to display are:

- Connection status for both the `eth0` and `wlan0` network interfaces
- Current IP address
- MAC address

As follow-up issue, we will [add a button to the Static IP and WiFi dialogs](https://github.com/tiny-pilot/tinypilot/issues/1826) that will direct the user to the Network Status dialog.

---

Original issue description:

> We can add some indicator to the UI, so that the user can review which network interfaces are active/available on the device (Ethernet, WiFi). This can either be something in the status bar, or we add that info to the WiFi dialog directly.
>
> In this process, we should also revisit whether and how we give feedback after the user entered their WiFi credentials in the WiFi dialog. We currently don’t verify at all whether the WiFi settings lead to a successful wireless connection – however, there are situations where this isn’t legitimately possible, or even undesired, e.g. if the user wants to preconfigure some WiFi settings without being in reach of the WiFi network.
>
> One technical note: after enabling WiFi, it might take a while (e.g., 5–10 seconds) for the WiFi connection to become available. We also may need to account for the fact what happens if a network disconnects (e.g., if the Ethernet cable is unplugged). One potential idea could be to update the indicator periodically, to reflect these changes.

**Comment by shalver-tp** [comment]
Does this indicator indicate to which interfaces the TinyPilot is connected?

Or does it indicate which interface the _user_ is using to connect to the TinyPilot at the moment?

Or both?

I think part of this will depend on the UI mockup, but there is a functionality aspect to it also.

**Comment by shalver-tp** [comment]
I was thinking that there was no way to functionally be able to tell which interface a user was connected to - thanks for confirming.

It doesn't 100% fit with the way "Connected" is currently employed in the bottom left, but I'm wondering if this new status could be part of the "Connected" Tool Tip that currently exists.  Something to explore.

Regardless of tool tip, or a separate item, I think a mockup would be helpful at this stage.  Thanks!

**Comment by cghague** [comment]
The status bar currently only includes information relevant to the client session (e.g., keystrokes, current video format, etc). We should keep system information separate to avoid confusion.

I suggest we follow the tried-and-tested icon approach, placing an unplugged network cable symbol and a disconnected Wi-Fi network symbol at the top right of the menu bar and toggling them to their connected variants based on active interfaces.

**Comment by shalver-tp** [comment]
@cghague  Great idea!

I'm unsure on whether we put it top right or bottom right.

An ethernet port and a wi-fi signal.
- grey for disconnected
- green for connected

One thing to keep in mind, we may want to expand this in the future if/when we add more ways to connect (LTE, Ethernet2, etc.)

**Comment by cghague** [comment]
Excellent points, @jotaen4tinypilot!

This feature mainly solves the lack of feedback a user receives when pre-configuring a Wi-Fi network. As a result, it's something they should only need to see a couple of times, so we should look at less prominent options. We've also had several requests lately from users who want to see the details of their network from the web interface. With the right solution, we could fix two problems at once here.

I've been considering the possibilities, and I suggest dropping the idea of a status indicator and adding a new dialog showing the status of the TinyPilot device's network interfaces instead. The user would be redirected to the dialog whenever they change a network setting via the web interface, and they could also access it manually from a new menu item.

This dialog approach would:

- Avoid cluttering the main interface (we'd put a new entry in the existing menu structure).
- Remove the need to poll for data, except when the dialog is active, in which case it could refresh every few seconds.
- Be relatively easy to implement within our existing design standards while solving several use cases.

I've made a (much less sophisticated) mockup of what I'm imagining:

![network-status-concept](https://github.com/user-attachments/assets/3ccde00c-b63f-476c-96a3-9c6faff7a24d)

Let me know your thoughts!

**Comment by shalver-tp** [comment]
This is good discussion, thanks.

I think the Tool Tip or the Network Dialog box are good options and solve a few problems (polling, not cluttering the UI), I don't necessarily have a strong preference for either at the moment.

One thing to keep in mind is needing to potentially expand this information if/when we add more NICs in future hardware (2nd Eth, LTE).

**Questions to think about:**
Does moving this to a network status dialog box lend itself to display more interfaces in the future in a way that the tooltip does not?

Does _eventually_ (still no timeline) moving to Bookworm (and Network Manager) change how we would approach this?

**Comment by cghague** [comment]
A scrollable dialog could show as many interfaces as required and would be more touchscreen-friendly, which might be a factor given the focus of our latest release. Tooltips are good for transiently providing a small amount of information, so they aren't a good fit in this case.

Based on my understanding, the front-end web interface is essentially a display layer, and moving to Bookworm shouldn't affect our choices here. However, I'll defer to @jotaen4tinypilot on that topic, as he is more familiar with the app than I am!

**Comment by shalver-tp** [comment]
> I’ve started to work on a new “Network Status” dialog, which could roughly look like so:


I think this Network Status dialog looks nice and clean.

> IP address, subnet mask, and router IP address: might be helpful when configuring static IP for the eth0 interface. Does it make sense to display this for the wlan0 interface too?
MAC address: do we need this? Or what would be the use-case here?
WiFi SSID: do we want to repeat this here, or is it sufficient to provide this info in the WiFi dialog?
Technical interface names: shall we display the technical interface names such as eth0 and wlan0 somewhere? Or is this an implementation detail that’s unimportant to the user?


I think the data shown currently is the minimum we should show. If we wanted to show the other data, I think we would want it hidden until a user requests "more info." At the same time, I think this is a good iteration and doesn't need anything else.  @cghague Do you have thoughts?

> How do we want to direct the user to this new dialog? So far, we don’t have any UI pattern for jumping directly from one dialog to the other. One option would be to place a button at the end e.g. the WiFi dialog, so that the user can optionally (if desired) go to the “Network Status” dialog.

I think the dialog boxes (Network status and the Wi-Fi with the "jump" button look good).

I don't think we automatically route someone to network status after a Wi-Fi credential is input.


> Semi-related to the point of which data to present would be the question whether we want to build a complete version of this new dialog right from the start, or whether it’s viable for us to approach this iteratively? For example, we could start to display the basic information that we already have, and then extend the dialog with more info once it’s released. (See also my other note below about determining the info from the system.)

_I would think we iterate at this point_, however, this brings up another topic. As we build out more network connectivity in the next 2-6 months, do we eventually roll a lot of this into a general purpose "Network Setup" dialog box?  I would think eventually yes, otherwise we might end up with:  adjust Wi-fi here, set Static IP here, setup 2nd Eth here, setup LTE here, etc.

**Comment by cghague** [comment]
Thanks, @jotaen4tinypilot, that's an excellent, clean design!

### Data to present

My suggestion for a first iteration would be that we show the following basic information:

- Connected state - Solves the Wi-Fi indicator issue.
- IP address - Useful for troubleshooting and helps us identify connections that are up but using self-assigned addresses.
- MAC address - This is an easy win and would solve a few recent tickets regarding physical layer authentication.

I'm ambivalent about showing the Wi-Fi network name in this dialog, but if we choose to include it, we should only show it when it's actively connected.

We should avoid using interface names in this dialog, at least for now, as they will confuse non-technical users. The users they'll be relevant to will already know how to find them over SSH.

I recommend against a "Show Details" button, as it's an anti-pattern that users find obstructive and confusing. Instead, we should focus on a clean design that shows only the most useful information.

### Directing users from other dialogs

My preference is to offer a button to open this dialog on the success dialog shown after applying a Static IP address or storing a Wi-Fi network. An automatic redirection would make the process confusing.

### Determining the info from the system

We can obtain network information in several ways, such as using the JSON output from the `ip` command. When you reach the implementation stage, I can help with the details if needed.

### Consolidating the networking features

I mentioned this at one of our previous team meetings, so I'm naturally supportive of the idea! This dialog could be a good launchpad for network settings in the future, such as by adding buttons or links to each feature.

**Comment by cghague** [comment]
Thanks, @jotaen4tinypilot!

You are correct about the output of the `ip` command. The `inet` object is for IPv4, and `inet6` is for IPv6. We only need IPv4 for now. Multiple blocks with the same family will exist if/when we get to IPv6, but it should be safe to assume there will only be a single `inet` object until then.

You can exclude the `eth0` argument to get the details for all interfaces simultaneously if that would simplify the implementation, but that's entirely up to your preference!

The demo looks excellent!
