### ISSUE TITLE
Clarify that setting a static IP only applies to Ethernet, not WiFi

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#1815]
Related https://github.com/tiny-pilot/tinypilot/issues/131. (Originally subtask (e)).

Setting a static IP address for the device only applies to the Ethernet interface, but it doesn’t have an effect on WiFi. This is not obvious to users, so we should clarify this e.g. in the static IP dialog.

**Comment by shalver-tp** [comment]
@jotaen4tinypilot 

I think trying to make it more concise is valuable.

I'd also think about making the "Note" section called out in a different color. You could Then simplify that text to "Setting a static IP only affects the Ethernet connection."

I think there are some places in the UI that use a different color or box to call out (see "Security Settings").

I'd love @cghague to weigh in also when he has a chance.

**Comment by shalver-tp** [comment]
@jotaen4tinypilot I agree the orange/red is too harsh.

I'm not completely averse to adding a new style, but I'll wait for Charles' take on how critical this note might be.

**Comment by cghague** [comment]
@shalver-tp / @jotaen4tinypilot - We already use the blue callouts in some of our [frequently asked questions](https://tinypilotkvm.com/faq/enable-audio), and I think we'd benefit from extending that pattern into the app as well. We should use it sparingly, but I think it's a good choice for this particular scenario in the first instance.
