### ISSUE TITLE
Support audio

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#276]
I'm not sure how feasible this is given TinyPilot's current recommended hardware. If we can't forward the sound, it might be sufficient to detect that a sound event occurred on the remote machine and somehow give a visual indicator in the TinyPilot interface.

**Comment by cagnulein** [comment]
so no sound at all? doesn't the input hdmi usb support this?

**Comment by mtlynch** [comment]
Some HDMI capture devices support sound, but we also need to pipe sound through the rest of the system. We're transmitting the remote screen in MJPEG format, which doesn't support sound.

**Comment by mtlynch** [comment]
We're in the process of working on H264 support in #875

**Comment by 1nnovat1on** [comment]
I also would greatly benefit from this feature

**Comment by mtlynch** [comment]
This is now fixed and available in Voyager 2a devices or DIY devices that have audio-aware HDMI capture.
