### ISSUE TITLE
Url to go directly To "Fullscreen" within an iframe

### ISSUE THREAD

**Issue by ldimaggiott** [tiny-pilot/tinypilot#523]
I'm using the TinyPilot Url in an iframe on another internal site and I was wondering if there was a URL that would make it render "fullscreen" within the iframe?

Thanks for your work on this! Really a dream product.

**Comment by mtlynch** [comment]
Oh, that's a good idea!

It's currently not possible, but it's a good idea for the future.

**Comment by mtlynch** [comment]
Merging this into #728
