### ISSUE TITLE
Refactor attachShadow calls

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#718]
All of our HTML custom elements include this snippet:

```javascript
this.attachShadow({ mode: "open" })
this.shadowRoot.appendChild(template.content.cloneNode(true));
```

But `attachShadow` [returns the shadow root](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow), so we can just do it in a single statement:

```javascript
this.attachShadow({ mode: "open" }).appendChild(template.content.cloneNode(true));
```

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by mtlynch** [comment]
@RhnSharma - Great! It's all yours.
