### ISSUE TITLE
Revise button style

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#743]
I'd like to see if we can improve on TinyPilot's current button style:

![image](https://user-images.githubusercontent.com/7783288/125684798-8a5acd5b-ce0f-40a4-8cbe-ee07e5b5dae7.png)

![image](https://user-images.githubusercontent.com/7783288/125684907-bf2d818d-29cd-43cb-8a13-cfdcf0b1d666.png)

To me, the buttons feel a bit too flat and square. I'd like to see if we can give them a bit more depth and smoothness.

I'd also like to reevaluate their size, as they sometimes feel too big to me relative to the adjacent content.

## Inspiration

Here are some buttons for products in a similar space that I think look good.

### Ubiquiti

![image](https://user-images.githubusercontent.com/7783288/125685147-6a4c190b-8eae-4562-a623-7a13b874abc5.png)

### OPNSense

![image](https://user-images.githubusercontent.com/7783288/125685189-4d00fcf7-417e-4610-8402-67a1887850de.png)

**Comment by jotaen4tinypilot** [comment]
Done.
