### ISSUE TITLE
Add support for custom commands

### ISSUE THREAD

**Issue by e-minguez** [tiny-pilot/tinypilot#787]
It would be nice to add support to run custom commands on the pi via the UI (for example to workaround #786 or #129 )

**Comment by e-minguez** [comment]
Something like https://plugins.octoprint.org/plugins/systemcommandeditor/

**Comment by mtlynch** [comment]
Thanks for the suggestion!

System Command Editor looks interesting, but unfortunately, this is too outside the scope of TinyPilot. Our design goal is that if the user needs to do a common task, we build intuitive web UI controls for it. For more niche tasks, the user would need to SSH in and type the commands directly. Adding a UI that supports arbitrary commands would be a pretty substantial effort.
