### ISSUE TITLE
Power Cycle PC / Turn on

### ISSUE THREAD

**Issue by wesleyscaldwell** [tiny-pilot/tinypilot#803]
The enterprise version is pretty awesome. 

The issue is that it seems to lock at times and it might be the computer. 

Scenario:
Editing BIOS
Mouse/Keyboard stop responding via pilot.
Go find computer and restart.

Feature:
Add connection option for Power
- Turn on PC
- Turn off PC
- Reset PC

**Comment by mtlynch** [comment]
Thanks for requesting this, @wesleyscaldwell!

We're currently tracking this idea in #80.

Would you prefer to have the TinyPilot connect directly to the ATX pins of the target machine? Or would you prefer that the TinyPilot controls an external power strip / cable and the target machine just connects to that power adaptor?

**Comment by wesleyscaldwell** [comment]
@mtlynch I think ATX pin is the better option. 
But that being said, maybe you can sell an add on relay module that connects to the pi. 

Because for more permanent locations it's worth it to hook up the ATX pins, but for ad-hoc support locations a simple relay outlet might be easier.
