### ISSUE TITLE
No libjpeg8-dev with Raspbian Bullseye

### ISSUE THREAD

**Issue by nicolas-schreiber** [tiny-pilot/tinypilot#809]
## Description

With Raspbian based on Debian Bullseye does not provide libjpeg8-dev, thus the install script fails

## What's the behavior that you expect?

Setup Script installing all we need

## What's happening instead?

```
TASK [ansible-role-ustreamer : install uStreamer pre-requisite packages] *******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'libjpeg8-dev' is available"}
```

## What are the steps to reproduce this behavior?

1. Setup fresh Raspbian with Bullseye
2. Run simple installation

**Comment by mtlynch** [comment]
Thanks for reporting this! We're tracking this in https://github.com/tiny-pilot/ansible-role-tinypilot/issues/143
