### ISSUE TITLE
Change USB output

### ISSUE THREAD

**Issue by majuss** [tiny-pilot/tinypilot#812]
Hi guys,

why can't I simply change the USB output (mouse and keyboard) to one of the USB-A ports and then connect an A-C cable to my computer which has USB-C? In that way I could also avoid the complicated powering issue...

**Comment by mtlynch** [comment]
Thanks for checking out the project!

Unfortunately, this is not possible. See #154.

**Comment by majuss** [comment]
I think it would be best practice to jsut use a tiny Arduino one thats based on the 32U4, stick it's USB into the target machine and the UART Bus to the arduino. That would also be an easy way to avoid the powering issue.
