### ISSUE TITLE
Clean up stale branches?

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/tinypilot#831]
We have a total of 314 branches right now, most of which [are stale](https://github.com/tiny-pilot/tinypilot/branches/stale). Can we delete them, or is there a reason for keeping them? Ditto for our other repos, though [in some it’s not as bad](https://github.com/tiny-pilot/tinypilot-pro/branches/stale).

[Here is one way of doing bulk-deleting](https://stackoverflow.com/a/69089905), which we could use. I’d be happy to take this on, it shouldn’t take long.

This is not a big deal at all, it just would make managing remote branches a bit easier, e.g. when QAing something or renaming a branch etc. Since we have auto-delete enabled in (I think) all of our repos, this problem should also not happen again.

(That’s how it looks in Git Tower)
<img width="260" alt="Screenshot 2021-11-26 at 17 27 50" src="https://user-images.githubusercontent.com/83721279/143609614-acee70a7-8570-4ad4-96ed-9202b1feb5f8.png">

**Comment by mtlynch** [comment]
Sure you can delete them. I'd like to preserve branches that were never merged into master, but it's not a big deal if we just delete everything stale if that's easier.

**Comment by mtlynch** [comment]
Closing, as we're now down to 67 branches, and they're unmerged branches that I'd like to keep around for posterity in case they're linked from bugs.
