### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by taylor-schneider** [tiny-pilot/tinypilot#856]
The [compatibility list](https://github.com/tiny-pilot/tinypilot/wiki/KVM-compatibility) shows an 8-port E-SDS switch as being fully compatible. If we follow the link there is a 2 port switch (not 8 port) shown on amazon. Can we update the readme with a correct description and add a column for model number?

**Comment by mtlynch** [comment]
Oh, that definitely used to link to an 8-port KVM. It looks like the Amazon seller swapped out the product.

I've updated it now. Thanks for letting me know.
