### ISSUE TITLE
Backup nginx configuration before installing

### ISSUE THREAD

**Issue by majuss** [tiny-pilot/tinypilot#864]
I'am running tinypilot on my main Pi which is also handling some webhosting. Tinypilot just obliterates any previous nginx config without any kind of backup. It should when installing and updating at least create a backup directory to store the previous nginx configs.

**Comment by mtlynch** [comment]
Sorry for wiping it! TinyPilot expects to own the nginx config, but the docs should make that clearer. I've submitted https://github.com/tiny-pilot/tinypilot/pull/869 to clarify.

This is unfortunately not something we'll fix. It would be possible to enable the [`backup` option](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-backup) when we [generate the nginx vhosts file](https://github.com/tiny-pilot/ansible-role-nginx/blob/f7cd5bf696a7c35f5328056d2585b515524824ad/tasks/vhosts.yml#L18), but that would clutter the directory with limitless backup files for every time we change the config. And solutions to limit the number of backup copies would also be too much complexity.
