### ISSUE TITLE
Multiple HDMI Connections

### ISSUE THREAD

**Issue by Johannp02180** [tiny-pilot/tinypilot#867]
Is it possible to have multiple HDMI adapters for different computers and access it from one raspberry pi? Maybe a menu option to select between the different sources?

**Comment by mtlynch** [comment]
You might be able to capture video output from multiple devices using multiple USB dongles, but the limiting factor is the USB OTG port. The Pi 4B has only one USB OTG port (the USB-C port), and that's required for emulating USB keyboard and mouse devices.

We're exploring native support for multiple targets in the Voyager 3.

In the meantime, some users hack multi-device support into TinyPilot by [chaining it to non-networked KVM switches](https://github.com/tiny-pilot/tinypilot/wiki/KVM-compatibility).
