### ISSUE TITLE
Capture KVM over unique USB-C ?

### ISSUE THREAD

**Issue by nodje** [tiny-pilot/tinypilot#872]
Would it be possible to capture display as well as keyboard-mouse over a single USB-C connection?
Some laptop now can share everything over a single USB-C cable, replacing a dock (displays, power, keyboard, mouse, etc.)

**Comment by mtlynch** [comment]
This is not possible. It might be possible in the future, but I think we'd have to patch the [Linux USB Gadget driver](https://www.kernel.org/doc/html/v4.19/driver-api/usb/gadget.html) in the kernel so that it can emulate a USB-C based display device.

**Comment by nodje** [comment]
Thanks, that'll be an interesting reading!
