### ISSUE TITLE
WHy use the Pi's USB-C rather than a std USB-A to connect target computer?

### ISSUE THREAD

**Issue by nodje** [tiny-pilot/tinypilot#873]
I'm even surprised it does work with the Pi4's USB-C which is supposed to be for Power (only?).
Is it to save a cable to power the PI or is it that it wouldn't work from one of the Pi4's 4 USB-A connectors?

**Comment by mtlynch** [comment]
Thanks for reaching out!

Unfortunately, the USB-A ports are not viable for this purpose. See #154 for details.

**Comment by nodje** [comment]
Got it, thanks for your prompt answer
