### ISSUE TITLE
Add H264 support

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#875]
This is a meta-bug to track the work we need to do in order to add H264 support to TinyPilot. Tasks are roughly in priority order.

- [x] https://github.com/tiny-pilot/ansible-role-tinypilot/issues/167
- [x] https://github.com/tiny-pilot/ansible-role-ustreamer/issues/49
- [x] https://github.com/tiny-pilot/ansible-role-tinypilot/issues/178
- [x] https://github.com/tiny-pilot/ansible-role-tinypilot/issues/179
- [x] https://github.com/tiny-pilot/ansible-role-tinypilot/issues/168
- [x] https://github.com/tiny-pilot/tinypilot/issues/877
- [x] https://github.com/tiny-pilot/tinypilot/issues/952
- [x] https://github.com/tiny-pilot/tinypilot/issues/946
- [x] https://github.com/tiny-pilot/tinypilot/issues/948
- [x] ~~https://github.com/tiny-pilot/tinypilot/issues/945~~
- [x] https://github.com/tiny-pilot/tinypilot/issues/956
- [x] https://github.com/tiny-pilot/ustreamer/issues/1

**Comment by jotaen4tinypilot** [comment]
The tasks above are all completed now 🎉 🥳 💃

**Comment by mtlynch** [comment]
Nice! Good work, everyone!
