### ISSUE TITLE
Use Janus to render remote screen in HTML client

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#877]
As part of [H264 integration](https://github.com/tiny-pilot/tinypilot/issues/875), we'll need to update our frontend JS/HTML code to interact with a Janus server and render the H264 stream in the browser.

We should add a Flask configuration option that controls whether the remote screen uses MJPEG or H264, even if for now, the only way to change that setting is manually editing the config file.

**Comment by jotaen4tinypilot** [comment]
Note to self, as mentioned by Jason via e-mail: the H264 stream might not be super robust yet, so we might want to consider what to do in case of video failure. (E.g., display some error message; automatically fall back to MJPEG; etc.)
