### ISSUE TITLE
Can the USB-C on RPi 4 be made *normal*

### ISSUE THREAD

**Issue by man4567890** [tiny-pilot/tinypilot#983]
Hi
When tiny-pilot runs, it looks like the *normal* USB functionality is disabled on the USB-C port, is there a way to switch the USB-C port on the RPi 4 back to *normal* operation? I need to run some tiny-pilot scripts, then switch back to *normal* USB functionality, then switch back to tiny-pilot. The only *way* I can get it to work is to set dtoverlay=dwc2,dr_mode=host in/boot/config.txt and then reboot, but is there another way please

**Comment by mtlynch** [comment]
TinyPilot needs the USB-C port to operate in device mode in order to emulate USB devices. It sounds like you also need it to run in host mode in order to receive other USB devices.

Unfortunately, I don't know of a way to switch between host mode and device mode without a reboot.
